<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;use Spatie\Permission\Models\{Permission,Role};use Spatie\Permission\PermissionRegistrar;
class TransportPermissionSeeder extends Seeder { public function run():void { app(PermissionRegistrar::class)->forgetCachedPermissions(); $permissions=[
 'transporte.ver','transporte.indicadores.ver','transporte.documentos.ver','transporte.documentos.gestionar','transporte.alertas.ver','transporte.alertas.gestionar','transporte.historico.ver','transporte.reportes.generar','transporte.configuracion.gestionar','transporte.rutas.ver','transporte.rutas.gestionar','transporte.vehiculos.ver','transporte.vehiculos.gestionar','transporte.conductores.ver','transporte.conductores.gestionar','transporte.pasajeros.ver','transporte.pasajeros.gestionar','transporte.programacion.ver','transporte.programacion.crear','transporte.programacion.editar','transporte.programacion.cancelar','transporte.servicios.ver','transporte.servicios.crear','transporte.servicios.editar','transporte.servicios.preparar','transporte.pasajeros_servicio.gestionar','transporte.operacion.ver','transporte.operacion.cerrar','transporte.preoperacional.gestionar','transporte.salida.registrar','transporte.llegada.registrar','transporte.llegada.corregir','transporte.pasajeros.operacion.gestionar','transporte.recursos.cambiar','transporte.novedades.ver','transporte.novedades.crear','transporte.novedades.gestionar','transporte.firmas.ver','transporte.reportes.ver','transporte.reportes.exportar','transporte.reportes.programacion','transporte.reportes.operacion'];
 foreach($permissions as $name) Permission::firstOrCreate(['name'=>$name,'guard_name'=>'web']); foreach(['Super Admin','Administrador SGSST'] as $roleName) if($role=Role::where('name',$roleName)->first())$role->givePermissionTo($permissions);
 // Rol dedicado y aislado al módulo de Transporte: acceso completo aquí, ningún permiso del resto de SG-SST.
 Role::firstOrCreate(['name'=>'Coordinador de Transporte','guard_name'=>'web'])->givePermissionTo($permissions);
 app(PermissionRegistrar::class)->forgetCachedPermissions(); }
}
