<!doctype html><html lang="es"><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans;font-size:11px;color:#222}h1{text-align:center;font-size:17px}h2{font-size:13px;margin-top:18px}table{width:100%;border-collapse:collapse;margin:8px 0}th,td{border:1px solid #777;padding:5px}.meta td{border:0}.signature{margin-top:50px}.signature td{border:0;text-align:center;padding-top:40px}</style></head><body>
<h1>{{ $formation->committee->type->value==='COPASST'?'ACTA DE CONFORMACIÓN DEL COMITÉ PARITARIO DE SEGURIDAD Y SALUD EN EL TRABAJO — COPASST':'ACTA DE CONFORMACIÓN DEL COMITÉ DE CONVIVENCIA LABORAL' }}</h1>
<table class="meta"><tr><td><b>Empresa:</b> {{$formation->committee->company->razon_social}}</td><td><b>NIT:</b> {{$formation->committee->company->nit}}</td></tr><tr><td><b>Acta:</b> {{$formation->act_number}}</td><td><b>Fecha:</b> {{$formation->formation_date->format('d/m/Y')}}</td></tr></table>
<h2>Antecedentes y fundamento normativo</h2><p>Concluidos la convocatoria, elección, cierre, escrutinio y validación de resultados, se formaliza la integración del comité. La integridad electoral validada corresponde a <b>{{$formation->electoral_snapshot['integrity_hash']}}</b>.</p><p>{{$formation->regulation_reference}}</p>
<h2>Composición definitiva</h2><p>Trabajadores considerados: {{$formation->workers_count_snapshot}}. Vigencia: {{$formation->effective_from->format('d/m/Y')}} — {{$formation->effective_to->format('d/m/Y')}}.</p>
<table><tr><th>Nombre</th><th>Cargo laboral</th><th>Representación</th><th>Condición</th></tr>@foreach($formation->period->members as $member)<tr><td>{{$member->employee->nombre_completo}}</td><td>{{$member->employee->cargo}}</td><td>{{$member->representation_type->value==='employer'?'Empleador':'Trabajadores'}}</td><td>{{$member->member_type->value==='principal'?'Principal':'Suplente'}}</td></tr>@endforeach</table>
<h2>Cargos</h2><table><tr><th>Cargo</th><th>Integrante</th><th>Método</th><th>Vigencia</th></tr>@foreach($formation->period->roles as $role)<tr><td>{{$role->role==='president'?'Presidente':'Secretario'}}</td><td>{{$role->member->employee->nombre_completo}}</td><td>{{str_replace('_',' ',$role->designation_method)}}</td><td>{{$role->starts_at->format('d/m/Y')}} — {{$role->ends_at->format('d/m/Y')}}</td></tr>@endforeach</table>
@if($formation->communication_date)<p><b>Comunicación:</b> {{$formation->communication_date->format('d/m/Y')}} {{$formation->communication_reference}}</p>@endif
<p>En constancia, queda formalmente conformado y activo el comité durante la vigencia indicada.</p><table class="signature"><tr><td>_____________________________<br>Presidente</td><td>_____________________________<br>Secretario</td></tr></table>
</body></html>
