<?php
namespace App\Services;
use App\Models\{AttendanceEvent,AttendanceParticipant,AttendanceRecord};use Illuminate\Support\Facades\{DB,Storage};use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
class AttendanceRegistrationService{
 public function __construct(private AttendanceEventService $events,private SignatureCaptureService $capture){}
 public function confirm(AttendanceEvent $event,AttendanceParticipant $participant,string $signatureData,bool $acknowledged):AttendanceRecord{
  if(!$acknowledged)throw ValidationException::withMessages(['acknowledged'=>'Debe confirmar el aviso de asistencia y tratamiento de datos.']);if($participant->attendance_event_id!==$event->id)abort(404);
  return DB::transaction(function()use($event,$participant,$signatureData){$event=AttendanceEvent::whereKey($event->id)->lockForUpdate()->firstOrFail();if(!$event->isOpen())throw ValidationException::withMessages(['event'=>'La asistencia ya no se encuentra abierta.']);$participant=AttendanceParticipant::whereKey($participant->id)->lockForUpdate()->firstOrFail();if($participant->record()->exists())throw ValidationException::withMessages(['attendance'=>'La asistencia ya fue registrada.']);$bytes=$event->requires_signature?$this->decodeSignature($signatureData):null;$now=now();$record=AttendanceRecord::create(['uuid'=>(string)Str::uuid(),'attendance_event_id'=>$event->id,'attendance_participant_id'=>$participant->id,'status'=>'confirmed','checked_in_at'=>$now,'confirmed_at'=>$now,'acknowledged_at'=>$now,'verification_method'=>'personal_code','verification_level'=>'standard','consent_text_version'=>config('attendance.consent_version'),'verification_code'=>strtoupper(Str::random(24))]);
   if($bytes!==null){$path='attendance/signatures/'.$event->uuid.'/'.$record->uuid.'.png';Storage::disk(config('attendance.disk'))->put($path,$bytes);$record->signature()->create(['signature_method'=>'drawn_signature','file_path'=>$path,'file_hash'=>hash('sha256',$bytes),'signed_at'=>$now,'verification_method'=>'personal_code','consent_text_version'=>config('attendance.consent_version')]);}
   if($event->attendable_type==='committee_meeting'&&$participant->employee_id){$meeting=$event->attendable;$meeting->attendees()->where('employee_id',$participant->employee_id)->update(['attendance_status'=>'present','arrival_time'=>$now->format('H:i:s')]);$meeting->load(['attendees.member','period']);$quorum=app(CommitteeQuorumService::class)->calculate($meeting);$meeting->update(['quorum_required'=>$quorum['required'],'quorum_present'=>$quorum['present'],'has_quorum'=>$quorum['has_quorum']]);}
   $payload=['attendance_event_uuid'=>$event->uuid,'attendance_record_uuid'=>$record->uuid,'participant_reference'=>$participant->uuid,'checked_in_at'=>$now->toIso8601String(),'signed_at'=>$now->toIso8601String(),'signature_file_hash'=>$record->signature?->file_hash,'verification_method'=>'personal_code','consent_text_version'=>config('attendance.consent_version')];$json=json_encode($payload,JSON_UNESCAPED_SLASHES);$key=config('attendance.evidence_key');$record->update(['evidence_hash'=>$key?hash_hmac('sha256',$json,$key):hash('sha256',$json)]);$this->events->audit($event,'attendance_registered',null,['record_id'=>$record->id]);if($bytes!==null)$this->events->audit($event,'signature_captured',null,['record_id'=>$record->id,'file_hash'=>$record->signature->file_hash]);return$record;
  });
 }
 private function decodeSignature(string $data):string{return$this->capture->decode($data,config('attendance.signature_max_bytes'));}
}
