<?php
namespace App\Services;
use App\Models\{AttendanceEvent,CommitteeMeeting};use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
class AttendanceEventService{
 public function createFromMeeting(CommitteeMeeting $meeting,array $data,int $userId):array{return DB::transaction(function()use($meeting,$data,$userId){$meeting->load(['committee','period.members.employee','period.members.roles']);if($meeting->attendanceEvent)throw ValidationException::withMessages(['event'=>'La reunión ya tiene un evento de asistencia.']);$token=Str::random(64);$event=AttendanceEvent::create(['company_id'=>$meeting->committee->perfil_empresa_id,'uuid'=>(string)Str::uuid(),'attendable_type'=>'committee_meeting','attendable_id'=>$meeting->id,'title'=>$meeting->committee->type->value==='CCL'?'Reunión Comité de Convivencia Laboral':$meeting->subject,'event_type'=>'committee_meeting','starts_at'=>$meeting->meeting_date->format('Y-m-d').' '.$meeting->start_time,'ends_at'=>$data['ends_at'],'attendance_opens_at'=>$data['attendance_opens_at'],'attendance_closes_at'=>$data['attendance_closes_at'],'status'=>'scheduled','requires_signature'=>$data['requires_signature']??true,'allows_external_attendees'=>$data['allows_external_attendees']??false,'public_access_enabled'=>true,'access_token_hash'=>hash('sha256',$token),'access_token_expires_at'=>$data['attendance_closes_at'],'created_by'=>$userId,'updated_by'=>$userId]);$codes=[];foreach($meeting->period->members()->whereIn('status',['active','designated'])->with(['employee','roles'])->get() as $member){$code=strtoupper(Str::random(10));$p=$event->participants()->create(['uuid'=>(string)Str::uuid(),'participant_type'=>'employee','employee_id'=>$member->employee_id,'name_snapshot'=>$member->employee->nombre_completo,'role_snapshot'=>$member->roles->pluck('role')->map(fn($r)=>$r==='president'?'Presidente':($r==='secretary'?'Secretario':ucfirst($r)))->implode(', ')?:($member->member_type->value==='principal'?'Principal':'Suplente'),'department_snapshot'=>$member->employee->area_departamento,'expected'=>true,'credential_hash'=>hash('sha256',$code),'credential_expires_at'=>$data['attendance_closes_at']]);$codes[]=['name'=>$p->name_snapshot,'code'=>$code];}$this->audit($event,'attendance_event_created',$userId,['participants'=>count($codes)]);$this->audit($event,'qr_generated',$userId);return compact('event','token','codes');});}
 public function rotate(AttendanceEvent $event,int $userId):string{$this->mutable($event);$token=Str::random(64);$event->update(['access_token_hash'=>hash('sha256',$token),'token_rotated_at'=>now(),'updated_by'=>$userId]);$this->audit($event,'qr_rotated',$userId);return$token;}
 public function open(AttendanceEvent $event,int $userId):void{
  if(!in_array($event->status,['draft','scheduled','open']))throw ValidationException::withMessages(['status'=>'Solo un evento programado o abierto puede habilitarse.']);
  if($event->attendance_closes_at&&now()->gte($event->attendance_closes_at))throw ValidationException::withMessages(['attendance_closes_at'=>'La fecha de cierre de la asistencia ya finalizó. Reprograme la sesión antes de abrirla.']);
  $changes=['status'=>'open','public_access_enabled'=>true,'updated_by'=>$userId];
  if(!$event->attendance_opens_at||now()->lt($event->attendance_opens_at))$changes['attendance_opens_at']=now();
  $event->update($changes);
  $this->audit($event,'attendance_event_opened',$userId,['manual'=>true,'attendance_opens_at'=>$event->attendance_opens_at?->toDateTimeString()]);
 }
 public function close(AttendanceEvent $event,int $userId):void{if($event->status!=='open')throw ValidationException::withMessages(['status'=>'Solo un evento abierto puede cerrarse.']);$event->update(['status'=>'closed','updated_by'=>$userId]);$this->audit($event,'attendance_event_closed',$userId);}
 public function finalize(AttendanceEvent $event,int $userId):void{if($event->status!=='closed')throw ValidationException::withMessages(['status'=>'Debe cerrar la asistencia antes de finalizarla.']);$event->update(['status'=>'finalized','updated_by'=>$userId]);$this->audit($event,'attendance_event_finalized',$userId);}
 public function audit(AttendanceEvent $event,string $action,?int $userId,array $metadata=[]):void{$event->audits()->create(['event'=>$action,'user_id'=>$userId,'metadata'=>$metadata,'created_at'=>now()]);}private function mutable($event){if(in_array($event->status,['finalized','cancelled']))throw ValidationException::withMessages(['event'=>'El evento está congelado y no admite cambios.']);}
}
