<?php
namespace App\Services;
use App\Enums\{CommitteeElectionStatus,CommitteeType};use App\Models\{Committee,CommitteeElection,CommitteeFormation,CommitteeMember,Empleado};use Carbon\Carbon;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
class CommitteeFormationFinalizationService {
 public function __construct(private CommitteeRegulationService $regulations,private CommitteeElectionResultService $results,private CommitteeFormationActService $acts){}
 public function preview(CommitteeElection $election):array {
  $election->load(['formationProcess.committee.company','formationProcess.period.members.employee','ties']);$process=$election->formationProcess;$composition=$this->regulations->composition($process->committee->type,$this->regulations->activeWorkersCount());$summary=$this->results->calculate($election);foreach($election->ties->where('status','resolved') as $tie){$priority=array_flip($tie->candidate_ids);usort($summary['results'],fn($a,$b)=>$b['votes']<=>$a['votes']?:($priority[$a['id']]??999)<=>($priority[$b['id']]??999));}$selected=collect($summary['results'])->take($composition['worker_principals']+$composition['worker_substitutes']);$employers=$process->period->members->filter(fn($m)=>$m->representation_type->value==='employer');$blockers=[];
  if($election->status!==CommitteeElectionStatus::READY_FOR_FORMATION)$blockers[]='Los resultados electorales todavía no están validados para conformación.';if($election->ties->where('status','pending')->isNotEmpty())$blockers[]='Existe un empate pendiente.';
  foreach(['principal'=>'employer_principals','substitute'=>'employer_substitutes'] as $type=>$field)if($employers->filter(fn($m)=>$m->member_type->value===$type)->count()!==$composition[$field])$blockers[]="Representantes del empleador {$type}: composición incompleta o excedida.";
  if($selected->count()!==$composition['worker_principals']+$composition['worker_substitutes'])$blockers[]='No hay suficientes representantes electos.';if($election->result_integrity_hash!==$summary['digest'])$blockers[]='La integridad electoral cambió después de su validación.';return compact('composition','summary','selected','employers','blockers');
 }
 public function finalize(CommitteeElection $election,array $data,int $userId):CommitteeFormation {return DB::transaction(function()use($election,$data,$userId){
  $election=CommitteeElection::whereKey($election->id)->lockForUpdate()->firstOrFail();$committee=Committee::whereKey($election->formationProcess->committee_id)->lockForUpdate()->firstOrFail();if($existing=$election->finalFormation()->first())return $existing;$preview=$this->preview($election);if($preview['blockers'])throw ValidationException::withMessages(['formation'=>$preview['blockers']]);
  if(!$election->closed_at||!$election->scrutinized_at||!$election->results_validated_at)throw ValidationException::withMessages(['election'=>'Faltan cierre, escrutinio o validación de resultados.']);$process=$election->formationProcess;$period=$process->period;$type=$committee->type;$formationDate=Carbon::parse($data['formation_date']);$effectiveFrom=Carbon::parse($data['effective_from']);if($formationDate->lt($election->results_validated_at->startOfDay()))throw ValidationException::withMessages(['formation_date'=>'La conformación no puede ser anterior a la validación de resultados.']);$latestDesignation=$period->members()->where('representation_type','employer')->max('designation_date');if($latestDesignation&&$effectiveFrom->lt(Carbon::parse($latestDesignation)))throw ValidationException::withMessages(['effective_from'=>'La vigencia no puede iniciar antes de la última designación del empleador.']);if($type===CommitteeType::CCL&&!$effectiveFrom->isSameDay(Carbon::parse($data['communication_date'])))throw ValidationException::withMessages(['effective_from'=>'Para Convivencia, la vigencia inicia en la fecha de comunicación.']);$effectiveTo=$effectiveFrom->copy()->addYears($this->regulations->termYears($type))->subDay();
  $period->members()->where('representation_type','employer')->update(['source_type'=>'employer_designation']);$rank=0;foreach($preview['selected'] as $row){$rank++;$candidate=$election->candidates()->with('sourceCandidate.employee')->findOrFail($row['id']);$employee=$candidate->sourceCandidate->employee;if(!$employee||!Empleado::active()->whereKey($employee->id)->exists())throw ValidationException::withMessages(['members'=>'Un candidato electo no está activo.']);if($period->members()->where('employee_id',$employee->id)->exists())throw ValidationException::withMessages(['members'=>'Un integrante electo ya aparece en el período.']);CommitteeMember::create(['committee_period_id'=>$period->id,'employee_id'=>$employee->id,'representation_type'=>'worker','member_type'=>$rank<=$preview['composition']['worker_principals']?'principal':'substitute','source_type'=>'worker_election','election_id'=>$election->id,'election_candidate_id'=>$candidate->id,'elected_votes'=>$row['votes'],'elected_rank'=>$rank,'designation_date'=>$formationDate,'status'=>'active','eligibility_confirmed'=>true,'eligibility_confirmed_by'=>$userId,'created_by'=>$userId,'updated_by'=>$userId]);}
  $period->load('members.employee');$president=$period->members->firstWhere('employee_id',(int)$data['president_employee_id']);$secretary=$period->members->firstWhere('employee_id',(int)$data['secretary_employee_id']);if(!$president||!$secretary)throw ValidationException::withMessages(['roles'=>'Los cargos deben asignarse a integrantes definitivos.']);if(!$this->regulations->canBePresident($type,$president))throw ValidationException::withMessages(['president_employee_id'=>'El Presidente COPASST debe representar al empleador.']);if(!$this->regulations->canBeSecretary($type,$secretary))throw ValidationException::withMessages(['secretary_employee_id'=>'Secretario no elegible.']);
  $period->update(['start_date'=>$effectiveFrom,'end_date'=>$effectiveTo,'status'=>'active','workers_count_snapshot'=>$preview['composition']['workers_count'],'regulation_reference'=>$preview['composition']['regulation_reference'],'updated_by'=>$userId]);$sequence=CommitteeFormation::whereYear('formation_date',$formationDate->year)->whereHas('committee',fn($q)=>$q->where('type',$type->value))->count()+1;
  $formation=CommitteeFormation::create(['committee_id'=>$committee->id,'committee_period_id'=>$period->id,'election_id'=>$election->id,'formation_date'=>$formationDate,'effective_from'=>$effectiveFrom,'effective_to'=>$effectiveTo,'communication_date'=>$data['communication_date']??null,'communication_reference'=>$data['communication_reference']??null,'communication_notes'=>$data['communication_notes']??null,'workers_count_snapshot'=>$preview['composition']['workers_count'],'regulation_reference'=>$preview['composition']['regulation_reference'],'regulation_snapshot'=>$preview['composition'],'electoral_snapshot'=>['integrity_hash'=>$election->result_integrity_hash,'results'=>$preview['summary']['results'],'validated_at'=>$election->results_validated_at?->toIso8601String()],'status'=>'forming','act_number'=>$type->value.'-'.$formationDate->year.'-'.str_pad($sequence,3,'0',STR_PAD_LEFT),'act_status'=>'generated','formed_by'=>$userId,'notes'=>$data['notes']??null]);
  foreach([['formation_started',[]],['worker_members_imported',['members'=>$rank]],['composition_validated',$preview['composition']]] as [$event,$meta])$this->audit($formation,$event,$userId,$meta);$period->roles()->create(['committee_member_id'=>$president->id,'role'=>'president','starts_at'=>$effectiveFrom,'ends_at'=>$this->regulations->presidentTermEndsAt($type,$effectiveFrom),'designation_method'=>$type===CommitteeType::COPASST?'employer_designation':'mutual_agreement','designation_date'=>$formationDate,'created_by'=>$userId]);$period->roles()->create(['committee_member_id'=>$secretary->id,'role'=>'secretary','starts_at'=>$effectiveFrom,'ends_at'=>$effectiveTo,'designation_method'=>$type===CommitteeType::COPASST?'committee_election':'mutual_agreement','designation_date'=>$formationDate,'created_by'=>$userId]);$this->audit($formation,'president_designated',$userId,['member_id'=>$president->id]);$this->audit($formation,'secretary_selected',$userId,['member_id'=>$secretary->id]);$this->acts->finalize($formation,$userId);$formation->update(['status'=>'active']);$committee->update(['status'=>'active','updated_by'=>$userId]);$process->update(['status'=>'active','updated_by'=>$userId]);$this->audit($formation,'formation_completed',$userId);$this->audit($formation,'formation_act_finalized',$userId,['document_id'=>$formation->documento_id]);$this->audit($formation,'committee_activated',$userId);return $formation->fresh();
 });}
 private function audit(CommitteeFormation $formation,string $event,int $userId,array $metadata=[]):void{$formation->audits()->create(['event'=>$event,'user_id'=>$userId,'metadata'=>$metadata,'created_at'=>now()]);}
}
