<?php
namespace App\Services; use App\Models\{TrainingAudit,TrainingEvaluation,TrainingEvaluationAccess,TrainingEvaluationAttempt,TrainingQuestion,TrainingReinforcement}; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
class TrainingEvaluationService
{
 public function publish(TrainingEvaluation$e,array$questionIds,int$user):array{if($e->status!=='draft')throw ValidationException::withMessages(['evaluation'=>'Solo un borrador puede publicarse.']);$bank=TrainingQuestion::forCompany($e->company_id)->where('training_topic_id',$e->training_topic_id)->whereIn('id',$questionIds)->where('is_active',true)->with('options')->get();if(!$bank->count())throw ValidationException::withMessages(['questions'=>'Seleccione preguntas válidas.']);return DB::transaction(function()use($e,$bank,$user){foreach($bank as$i=>$source){$q=$e->questions()->create(['source_question_id'=>$source->id,'question_text'=>$source->question_text,'question_type'=>$source->question_type,'explanation'=>$source->explanation,'points'=>$source->default_points,'is_critical'=>$source->is_critical,'sort_order'=>$i+1]);foreach($source->options as$o)$q->options()->create(['option_text'=>$o->option_text,'is_correct'=>$o->is_correct,'sort_order'=>$o->sort_order]);}$tokens=[];$participants=$e->session?->attendanceEvent?->participants()->whereNull('excluded_at')->get()??collect();foreach($participants as$p){if($e->requires_confirmed_attendance&&!$p->record()->where('status','confirmed')->exists())continue;$token=Str::random(64);$e->accesses()->create(['attendance_participant_id'=>$p->id,'token_hash'=>hash('sha256',$token),'expires_at'=>$e->closes_at,'enabled'=>true]);$tokens[]=['name'=>$p->name_snapshot,'url'=>route('training.evaluations.public.show',[$e,$token])];}$e->update(['status'=>'published','published_at'=>now(),'updated_by'=>$user]);$this->audit($e,'evaluation_published',$user,['participants'=>count($tokens)]);return$tokens;});}
 public function start(TrainingEvaluation$e,TrainingEvaluationAccess$a):TrainingEvaluationAttempt{return DB::transaction(function()use($e,$a){$last=$e->attempts()->where('attendance_participant_id',$a->attendance_participant_id)->lockForUpdate()->max('attempt_number')??0;if($e->maximum_attempts!==null&&$last>=$e->maximum_attempts)throw ValidationException::withMessages(['attempt'=>'Ya alcanzó el número máximo de intentos.']);$attempt=$e->attempts()->create(['uuid'=>(string)Str::uuid(),'attendance_participant_id'=>$a->attendance_participant_id,'employee_id'=>$a->participant->employee_id,'attempt_number'=>$last+1,'started_at'=>now(),'status'=>'started']);$this->audit($e,'attempt_started',null,['attempt_id'=>$attempt->id]);return$attempt;});}
 public function submit(TrainingEvaluationAttempt$a,array$answers,TrainingEvaluationScoringService$scoring):TrainingEvaluationAttempt{return DB::transaction(function()use($a,$answers,$scoring){$a=TrainingEvaluationAttempt::whereKey($a->id)->lockForUpdate()->firstOrFail();if($a->status!=='started')throw ValidationException::withMessages(['attempt'=>'Este intento ya fue enviado.']);$raw=0;$possible=0;foreach($a->evaluation->questions()->with('options')->get() as$q){$possible+=(float)$q->points;$result=$scoring->scoreQuestion($q,$answers[$q->id]??[]);$raw+=$result['points'];$a->answers()->create(['evaluation_question_id'=>$q->id,'selected_option_ids'=>$answers[$q->id]??[],'points_awarded'=>$result['points'],'is_correct'=>$result['correct']]);}$percentage=$scoring->calculatePercentage($raw,$possible);$result=$scoring->determineResult($percentage,(float)$a->evaluation->passing_score);$a->update(['submitted_at'=>now(),'raw_score'=>$raw,'possible_score'=>$possible,'percentage_score'=>$percentage,'result'=>$result,'status'=>'graded']);$this->audit($a->evaluation,'attempt_graded',null,['attempt_id'=>$a->id,'result'=>$result]);if($result==='failed'&&$a->evaluation->requires_reinforcement)TrainingReinforcement::firstOrCreate(['evaluation_attempt_id'=>$a->id],['company_id'=>$a->evaluation->company_id,'employee_id'=>$a->employee_id,'training_session_id'=>$a->evaluation->training_session_id,'reason'=>'Resultado de evaluación no aprobado; requiere refuerzo.','status'=>'pending','assigned_at'=>now(),'created_by'=>$a->evaluation->created_by]);return$a->fresh('answers');});}
 public function portalAccessToken(TrainingEvaluationAccess$a):string{$token=Str::random(64);$a->update(['token_hash'=>hash('sha256',$token)]);return$token;}
 public function findAccess(TrainingEvaluation$e,string$token):TrainingEvaluationAccess{$a=$e->accesses()->where('token_hash',hash('sha256',$token))->where('enabled',true)->with('participant.record')->firstOrFail();if($e->opens_at&&now()->lt($e->opens_at))abort(403,'La evaluación todavía no está abierta.');if(($a->expires_at&&now()->gte($a->expires_at))||($e->closes_at&&now()->gte($e->closes_at)))abort(410,'El acceso a la evaluación venció.');if(!in_array($e->status,['published','open']))abort(403,'La evaluación no está disponible.');$a->update(['last_accessed_at'=>now()]);return$a;}
 private function audit($e,$event,$user,$meta=[]){TrainingAudit::create(['company_id'=>$e->company_id,'event'=>$event,'subject_type'=>'training_evaluation','subject_id'=>$e->id,'user_id'=>$user,'metadata'=>$meta,'created_at'=>now()]);}
}
