<?php
namespace App\Services; use App\Models\TrainingSession; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class TrainingSessionClosureService
{
 public function __construct(private TrainingProgressService$progress,private TrainingSessionService$sessions){}
 public function checklist(TrainingSession$s):array{$event=$s->attendanceEvent;$confirmed=$event?->records()->where('status','confirmed')->count()??0;$expected=$event?->participants()->where('expected',true)->whereNull('excluded_at')->count()??0;$types=$s->evidences()->pluck('evidence_type');return['execution_completed'=>in_array($s->status,['completed','closed']),'instructor'=>(bool)($s->instructor_employee_id||$s->external_instructor_id),'duration'=>$s->actual_duration_minutes!==null,'attendance'=>!$s->requires_attendance||($event&&in_array($event->status,['closed','finalized'])),'material'=>!$s->requires_material||$types->contains('training_material'),'execution_report'=>!$s->requires_execution_report||$types->contains('execution_report'),'expected'=>$expected,'confirmed'=>$confirmed];}
 public function calculateCoverage(TrainingSession$s):float{$event=$s->attendanceEvent;if(!$event)return 0.0;$expected=$event->participants()->where('expected',true)->whereNull('excluded_at')->count();$confirmed=$event->records()->where('status','confirmed')->count();return $this->coverageFromCounts($expected,$confirmed);}
 public function coverageFromCounts(int$expected,int$confirmed):float{return $expected>0?round(($confirmed/$expected)*100,2):0.0;}
 public function close(TrainingSession$s,int$user):void{$check=$this->checklist($s);$missing=collect($check)->except(['expected','confirmed'])->filter(fn($ok)=>!$ok)->keys()->map(fn($key)=>config('training.closure_checklist_labels.'.$key,ucfirst(str_replace('_',' ',$key))))->all();if($missing)throw ValidationException::withMessages(['closure'=>'No se puede cerrar. Faltan: '.implode(', ',$missing).'.']);DB::transaction(function()use($s,$user){$coverage=$this->calculateCoverage($s);$s->update(['status'=>'closed','coverage_percentage'=>$coverage,'updated_by'=>$user]);if($s->programItem)$this->progress->update($s->programItem);$this->sessions->audit($s,'training_session_closed',$user,['coverage'=>$coverage]);});}
}
