<?php
namespace App\Services;
use App\Models\{TrainingAudit,TrainingProgramItem,TrainingSession};
use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
class TrainingSessionService
{
 public function create(array$data,int$company,int$user,?TrainingProgramItem$item=null):TrainingSession{return DB::transaction(function()use($data,$company,$user,$item){if($item&&$item->program->company_id!==$company)abort(403);if($item){$data=array_merge(['training_program_item_id'=>$item->id,'training_topic_id'=>$item->training_topic_id,'title'=>$item->title,'description'=>$item->description,'training_type'=>$item->training_type,'planned_duration_minutes'=>$item->estimated_duration_minutes?:60,'modality'=>$item->planned_modality,'audience_type'=>$item->target_population_type,'audience_description'=>$item->target_population_description],$data);}elseif(empty($data['extraordinary_reason']))throw ValidationException::withMessages(['extraordinary_reason'=>'Debe justificar la sesión extraordinaria.']);$session=TrainingSession::create(array_merge($data,['company_id'=>$company,'uuid'=>(string)Str::uuid(),'status'=>'draft','created_by'=>$user,'updated_by'=>$user]));$this->audit($session,'training_session_created',$user,['program_item_id'=>$item?->id]);return$session;});}
 public function schedule(TrainingSession$s,int$user):void{$this->mutable($s);if($s->scheduled_end_at->lte($s->scheduled_start_at))throw ValidationException::withMessages(['scheduled_end_at'=>'La hora final debe ser posterior a la hora inicial.']);$s->update(['status'=>'scheduled','updated_by'=>$user]);$this->audit($s,'training_session_scheduled',$user);}
 public function start(TrainingSession$s,int$user):void{if(!in_array($s->status,['called','attendance_open','scheduled']))throw ValidationException::withMessages(['status'=>'La sesión no está lista para iniciar.']);if(!$s->instructor_employee_id&&!$s->external_instructor_id)throw ValidationException::withMessages(['instructor'=>'Debe asignar instructor.']);if($s->requires_attendance&&!$s->attendance_event_id)throw ValidationException::withMessages(['attendance'=>'Debe habilitar la asistencia.']);$s->update(['status'=>'in_progress','actual_start_at'=>now(),'updated_by'=>$user]);$this->audit($s,'training_session_started',$user);}
 public function complete(TrainingSession$s,array$data,int$user):void{if($s->status!=='in_progress')throw ValidationException::withMessages(['status'=>'Solo una sesión en curso puede finalizarse.']);$end=now();$s->update(array_merge($data,['status'=>'completed','actual_end_at'=>$end,'actual_duration_minutes'=>$s->actual_start_at->diffInMinutes($end),'updated_by'=>$user]));$this->audit($s,'training_session_completed',$user);}
 public function reschedule(TrainingSession$s,$start,$end,string$reason,int$user):void{$this->mutable($s);$s->changes()->create(['change_type'=>'rescheduled','old_start_at'=>$s->scheduled_start_at,'new_start_at'=>$start,'old_end_at'=>$s->scheduled_end_at,'new_end_at'=>$end,'reason'=>$reason,'changed_by'=>$user,'changed_at'=>now()]);$s->update(['scheduled_start_at'=>$start,'scheduled_end_at'=>$end,'status'=>'rescheduled','updated_by'=>$user]);$this->audit($s,'training_session_rescheduled',$user,['reason'=>$reason]);}
 public function cancel(TrainingSession$s,string$reason,int$user):void{$this->mutable($s);$s->changes()->create(['change_type'=>'cancelled','old_start_at'=>$s->scheduled_start_at,'old_end_at'=>$s->scheduled_end_at,'reason'=>$reason,'changed_by'=>$user,'changed_at'=>now()]);$s->update(['status'=>'cancelled','notes'=>trim($s->notes."\nCancelación: ".$reason),'updated_by'=>$user]);$this->audit($s,'training_session_cancelled',$user,['reason'=>$reason]);}
 public function audit(TrainingSession$s,string$event,int$user,array$metadata=[]):void{TrainingAudit::create(['company_id'=>$s->company_id,'event'=>$event,'subject_type'=>'training_session','subject_id'=>$s->id,'user_id'=>$user,'metadata'=>$metadata,'created_at'=>now()]);}
 private function mutable(TrainingSession$s):void{if(in_array($s->status,['closed','cancelled']))throw ValidationException::withMessages(['session'=>'Una sesión cerrada o cancelada no puede modificarse.']);}
}
