<?php
namespace App\Services;
use App\Models\{Empleado,EmployeeTrainingCredential,TrainingAlert,TrainingProgram,TrainingProgramItem,TrainingReinforcement};
use Illuminate\Support\Collection;
class TrainingAlertService
{
 public function __construct(private TrainingGapService$gaps,private TrainingRequirementResolverService$resolver){}
 public function scan(int$companyId):array{$seen=[];$now=now();
  $program=TrainingProgram::forCompany($companyId)->where('year',$now->year)->latest('version')->first();
  if(!$program)$this->touch($companyId,'program:missing:'.$now->year,'planning','program_missing','critical','Programa anual ausente','No existe Programa Anual de Capacitación para la vigencia.',$seen);
  TrainingProgramItem::whereHas('program',fn($q)=>$q->where('company_id',$companyId))->whereIn('status',['planned','reprogrammed'])->whereDate('planned_date','<',$now)->get()->each(fn($item)=>$this->touch($companyId,'activity:overdue:'.$item->id,'execution','activity_overdue','warning','Actividad atrasada',$item->title,$seen,$item));
  EmployeeTrainingCredential::where('company_id',$companyId)->whereNotNull('expires_at')->get()->each(function($credential)use($companyId,$now,&$seen){$days=$now->startOfDay()->diffInDays($credential->expires_at,false);if($days<0)$this->touch($companyId,'credential:expired:'.$credential->id,'certification','credential_expired','critical','Certificado vencido',$credential->name,$seen,$credential,$credential->employee_id,$credential->expires_at);elseif($days<=max(config('training.alert_windows.credential_expiration_days',[30])))$this->touch($companyId,'credential:expiring:'.$credential->id,'certification','credential_expiring','warning','Certificado próximo a vencer',$credential->name.' vence en '.$days.' días.',$seen,$credential,$credential->employee_id,$credential->expires_at);});
  TrainingReinforcement::where('company_id',$companyId)->whereIn('status',['pending','scheduled','in_progress'])->whereNotNull('due_at')->where('due_at','<',$now)->get()->each(fn($r)=>$this->touch($companyId,'reinforcement:overdue:'.$r->id,'evaluation','reinforcement_overdue','critical','Refuerzo vencido',$r->reason,$seen,$r,$r->employee_id,$r->due_at));
  Empleado::where('company_id',$companyId)->active()->whereNotNull('fecha_ingreso')->get()->each(function($employee)use($companyId,&$seen){$induction=$this->resolver->routeFor($employee)->first(fn($r)=>str_contains(mb_strtolower($r['requirement']->topic->name),'inducci'));if($induction&&in_array($induction['status'],['pending','expired']))$this->touch($companyId,'induction:pending:'.$employee->id,'individual','induction_pending','critical','Inducción pendiente',$employee->nombre_completo.' no tiene inducción vigente registrada.',$seen,$employee,$employee->id);});
  foreach($this->gaps->forCompany($companyId)as$gap)$this->touch($companyId,'gap:'.$gap['key'],'individual','training_gap',$gap['priority']==='critical'?'critical':'warning','Requisito de formación pendiente',$gap['employee']->nombre_completo.' — '.$gap['requirement']->topic->name,$seen,$gap['requirement'],$gap['employee']->id,$gap['expires']);
  TrainingAlert::forCompany($companyId)->whereIn('status',['open','acknowledged'])->whereNotIn('alert_key',$seen?:['__none__'])->update(['status'=>'resolved','resolved_at'=>$now]);
  return['detected'=>count($seen),'open'=>TrainingAlert::forCompany($companyId)->where('status','open')->count()];}
 private function touch(int$c,string$key,string$category,string$type,string$severity,string$title,string$message,array&$seen,$subject=null,$employeeId=null,$dueAt=null):void{$seen[]=$key;$values=['category'=>$category,'type'=>$type,'severity'=>$severity,'title'=>$title,'message'=>$message,'employee_id'=>$employeeId,'due_at'=>$dueAt,'last_detected_at'=>now()];if($subject){$values['subject_type']=$subject::class;$values['subject_id']=$subject->getKey();}$alert=TrainingAlert::updateOrCreate(['company_id'=>$c,'alert_key'=>$key],$values);if(in_array($alert->status,['resolved','dismissed']))$alert->update(['status'=>'open','resolved_at'=>null,'resolved_by'=>null]);}
 public function acknowledge(TrainingAlert$a,int$userId):void{$a->update(['status'=>'acknowledged','acknowledged_at'=>now(),'acknowledged_by'=>$userId]);}
 public function resolve(TrainingAlert$a,int$userId,?string$notes):void{$a->update(['status'=>'resolved','resolved_at'=>now(),'resolved_by'=>$userId,'resolution_notes'=>$notes]);}
}
