<?php
namespace App\Services;
use App\Models\{TransportChecklistTemplate,TransportPreoperationalCheck,TransportService,TransportSetting,TransportVehicle,TransportPerson};
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class TransportOperationService
{
 public function __construct(private TransportAuditService $audit,private PrivateSignatureStorageService $signatures){}
 private function fail(string $message,string $field='service'):never{throw ValidationException::withMessages([$field=>$message]);}
 private function locked(TransportService $service):TransportService{return TransportService::forCompany($service->company_id)->whereKey($service->id)->lockForUpdate()->firstOrFail();}
 public function completePreoperational(TransportService $service,array $data,int $userId):void
 {
  DB::transaction(function()use($service,$data,$userId){$service=$this->locked($service);if($service->status!=='ready')$this->fail('Solo un servicio listo puede completar el control preoperacional.');
   $template=TransportChecklistTemplate::forCompany($service->company_id)->with('items')->whereKey($data['template_id'])->where('status','active')->firstOrFail();
   $answers=collect($data['results'])->keyBy('item_id');foreach($template->items as$item)if($item->is_required&&!$answers->has($item->id))$this->fail("Debe responder: {$item->label}",'results');
   $critical=$template->items->contains(fn($item)=>$item->is_critical&&($answers->get($item->id)['result']??null)==='non_compliant');
   if($critical&&$template->blocks_on_critical_failure&&empty($data['override_reason']))$this->fail('Existe un ítem crítico no conforme. Se requiere autorización y justificación.','override_reason');
   $check=TransportPreoperationalCheck::updateOrCreate(['transport_service_id'=>$service->id],['company_id'=>$service->company_id,'transport_checklist_template_id'=>$template->id,'status'=>'completed','completed_at'=>now(),'completed_by'=>$userId,'override_reason'=>$data['override_reason']??null,'override_by'=>$critical?$userId:null]);
   $check->results()->delete();foreach($data['results']as$result)$check->results()->create(['transport_checklist_item_id'=>$result['item_id'],'result'=>$result['result'],'observation'=>$result['observation']??null]);$service->update(['status'=>'preoperational']);$this->audit->record($service->company_id,'transport_preoperational_completed','service',$service->id,$userId,['critical_override'=>$critical]);
  });
 }
 public function departure(TransportService $service,array $data,int $userId):void
 {
  DB::transaction(function()use($service,$data,$userId){$service=$this->locked($service);if($service->status!=='preoperational'||$service->actual_start_at)$this->fail('La salida ya fue registrada o el preoperacional no está completo.');$setting=TransportSetting::where('company_id',$service->company_id)->first();if($setting?->requires_departure_odometer&&$data['departure_odometer']===null)$this->fail('El kilometraje de salida es obligatorio.','departure_odometer');
   $service->update(['actual_vehicle_id'=>$service->planned_vehicle_id,'actual_driver_id'=>$service->planned_driver_id,'actual_monitor_id'=>$service->planned_monitor_id,'actual_start_at'=>now(),'departure_odometer'=>$data['departure_odometer']??null,'departure_registered_by'=>$userId,'status'=>'in_progress']);$this->audit->record($service->company_id,'transport_departure_registered','service',$service->id,$userId);
  });
 }
 public function passenger(TransportService $service,int $rowId,string $status,int $userId):void
 {DB::transaction(function()use($service,$rowId,$status,$userId){$service=$this->locked($service);if($service->status!=='in_progress')$this->fail('Los pasajeros solo pueden actualizarse durante el servicio.');$row=$service->passengers()->whereKey($rowId)->lockForUpdate()->firstOrFail();$row->update(['status'=>$status,'status_recorded_at'=>now(),'status_recorded_by'=>$userId]);$this->audit->record($service->company_id,'transport_passenger_marked_'.$status,'service',$service->id,$userId,['passenger_row_id'=>$row->id]);});}
 public function changeResource(TransportService $service,string $type,int $resourceId,string $reason,int $userId):void
 {DB::transaction(function()use($service,$type,$resourceId,$reason,$userId){$service=$this->locked($service);if($service->status!=='in_progress')$this->fail('Los recursos solo pueden cambiarse durante un servicio en curso.');if(!in_array($type,['vehicle','driver','monitor'],true))abort(404);$model=$type==='vehicle'?TransportVehicle::class:TransportPerson::class;$resource=$model::forCompany($service->company_id)->whereKey($resourceId)->where('status','active')->firstOrFail();if($type==='driver'&&!$resource->is_driver)$this->fail('La persona seleccionada no está habilitada como conductor.');if($type==='monitor'&&!$resource->is_monitor)$this->fail('La persona seleccionada no está habilitada como monitor.');if($type==='vehicle'&&$service->actual_passenger_count>$resource->capacity)$this->fail('El vehículo no tiene capacidad suficiente.');
   $field='actual_'.$type.'_id';$old=$service->$field?:$service->{'planned_'.$type.'_id'};$conflict=TransportService::forCompany($service->company_id)->whereKeyNot($service->id)->where('status','in_progress')->where($field,$resourceId)->exists();if($conflict)$this->fail('El recurso está siendo utilizado por otro servicio en curso.');$service->update([$field=>$resourceId]);$service->changes()->create(['change_type'=>$type.'_change','old_data'=>[$field=>$old],'new_data'=>[$field=>$resourceId],'reason'=>$reason,'changed_by'=>$userId,'changed_at'=>now()]);$this->audit->record($service->company_id,'transport_'.$type.'_changed','service',$service->id,$userId,['old'=>$old,'new'=>$resourceId,'reason'=>$reason]);});}
 public function arrival(TransportService $service,array $data,int $userId):void
 {DB::transaction(function()use($service,$data,$userId){$service=$this->locked($service);if($service->status!=='in_progress'||$service->actual_arrival_at)$this->fail('La llegada ya fue registrada o el servicio no está en curso.');if(isset($data['arrival_odometer'],$service->departure_odometer)&&(float)$data['arrival_odometer']<(float)$service->departure_odometer)$this->fail('El kilometraje de llegada no puede ser menor al de salida.','arrival_odometer');$setting=TransportSetting::where('company_id',$service->company_id)->first();if($setting?->requires_arrival_odometer&&$data['arrival_odometer']===null)$this->fail('El kilometraje de llegada es obligatorio.','arrival_odometer');if($setting?->requires_arrival_signature&&empty($data['signature']))$this->fail('La firma de recepción es obligatoria.','signature');$now=now();$signature=null;if(!empty($data['signature'])){$bytes=$this->signatures->decodePng($data['signature']);$stored=$this->signatures->store("transport/arrival-signatures/{$service->uuid}/arrival.png",$bytes);$payload=['transport_service_uuid'=>$service->uuid,'arrival_at'=>$now->toIso8601String(),'receiver_reference'=>$data['receiver_employee_id']??$data['receiver_name']??null,'signature_file_hash'=>$stored['hash'],'vehicle_reference'=>$service->actual_vehicle_id,'driver_reference'=>$service->actual_driver_id,'evidence_version'=>1];$json=json_encode($payload,JSON_UNESCAPED_SLASHES);$key=config('attendance.evidence_key');$signature=['company_id'=>$service->company_id,'file_path'=>$stored['path'],'file_hash'=>$stored['hash'],'evidence_hash'=>$key?hash_hmac('sha256',$json,$key):hash('sha256',$json),'evidence_version'=>1,'signed_at'=>$now,'captured_by'=>$userId];}
   $service->update(['actual_arrival_at'=>$now,'arrival_odometer'=>$data['arrival_odometer']??null,'arrival_registered_by'=>$userId,'arrival_receiver_employee_id'=>$data['receiver_employee_id']??null,'arrival_receiver_name'=>$data['receiver_name']??null,'arrival_observation'=>$data['observation']??null,'status'=>'arrived']);if($signature)$service->arrivalSignature()->create($signature);$this->audit->record($service->company_id,'transport_arrival_registered','service',$service->id,$userId);if($signature)$this->audit->record($service->company_id,'transport_arrival_signature_captured','service',$service->id,$userId,['file_hash'=>$signature['file_hash']]);
  });}
 public function close(TransportService $service,int $userId):void{DB::transaction(function()use($service,$userId){$service=$this->locked($service);if($service->status!=='arrived')$this->fail('Solo un servicio con llegada registrada puede cerrarse.');if($service->issues()->where('status','open')->exists())$this->fail('Debe resolver las novedades abiertas antes de cerrar.');$service->update(['status'=>'closed','closed_at'=>now(),'closed_by'=>$userId]);$this->audit->record($service->company_id,'transport_service_closed','service',$service->id,$userId);});}
 public function interrupt(TransportService $service,string $reason,int $userId):void{DB::transaction(function()use($service,$reason,$userId){$service=$this->locked($service);if(!in_array($service->status,['preoperational','in_progress'],true))$this->fail('El servicio no puede interrumpirse en su estado actual.');$service->update(['status'=>'interrupted','interrupted_at'=>now(),'interrupted_by'=>$userId,'interruption_reason'=>$reason]);$this->audit->record($service->company_id,'transport_service_interrupted','service',$service->id,$userId,['reason'=>$reason]);});}
 public function correctTime(TransportService $service,string $field,string $value,string $reason,int $userId):void{DB::transaction(function()use($service,$field,$value,$reason,$userId){$service=$this->locked($service);if(!in_array($field,['actual_start_at','actual_arrival_at'],true))abort(404);if(!$service->$field)$this->fail('No existe un registro previo para corregir.',$field);$new=\Carbon\Carbon::parse($value);if($field==='actual_arrival_at'&&$service->actual_start_at&&$new->lt($service->actual_start_at))$this->fail('La llegada corregida no puede ser anterior a la salida.',$field);if($field==='actual_start_at'&&$service->actual_arrival_at&&$new->gt($service->actual_arrival_at))$this->fail('La salida corregida no puede ser posterior a la llegada.',$field);$old=$service->$field->toDateTimeString();$service->update([$field=>$new]);$service->changes()->create(['change_type'=>'operation_correction','old_data'=>[$field=>$old],'new_data'=>[$field=>$new->toDateTimeString()],'reason'=>$reason,'changed_by'=>$userId,'changed_at'=>now()]);$this->audit->record($service->company_id,'transport_operation_corrected','service',$service->id,$userId,['field'=>$field,'old'=>$old,'new'=>$new->toDateTimeString(),'reason'=>$reason]);});}
}
