<?php
namespace App\Services;
use App\Models\{TransportAlert,TransportDocument,TransportDocumentType,TransportPerson,TransportVehicle};use Illuminate\Support\Facades\DB;
class TransportDocumentControlService {
 public function store(array$d,$file,int$company,int$user):TransportDocument{return DB::transaction(function()use($d,$file,$company,$user){$type=TransportDocumentType::forCompany($company)->whereKey($d['transport_document_type_id'])->where('is_active',1)->firstOrFail();abort_unless($type->applies_to===$d['resource_type'],422);foreach(['number'=>'document_number','issue_date'=>'issued_at','expiration_date'=>'expires_at']as$require=>$field)if($type->{'requires_'.$require}&&empty($d[$field]))abort(422,"El tipo documental exige {$field}.");if($type->requires_file&&!$file)abort(422,'El tipo documental exige un archivo.');$name=$this->resourceName($company,$d['resource_type'],$d['resource_id']??null,$d['resource_name']??null);$stored=[];if($file){$bytes=file_get_contents($file->getRealPath());$stored=['file_path'=>$file->store('transport/documents',config('attendance.disk','local')),'file_hash'=>hash('sha256',$bytes),'original_name'=>$file->getClientOriginalName(),'mime_type'=>$file->getMimeType()];}if(!empty($d['supersedes_document_id'])){$old=TransportDocument::forCompany($company)->findOrFail($d['supersedes_document_id']);abort_unless($old->resource_type===$d['resource_type']&&(int)$old->resource_id===(int)($d['resource_id']??0),422);$old->update(['is_current'=>false,'updated_by'=>$user]);}$doc=TransportDocument::create(collect($d)->except(['resource_name','file'])->all()+$stored+['company_id'=>$company,'resource_name_snapshot'=>$name,'is_current'=>true,'created_by'=>$user]);return$doc;});}
 public function scan(int$company):int{$seen=[];$docs=TransportDocument::forCompany($company)->with('type')->where('is_current',1)->whereNotNull('expires_at')->get();foreach($docs as$d){$status=$d->control_status;if(!in_array($status,['expired','expiring']))continue;$key="transport:{$d->resource_type}:{$d->resource_id}:document:{$d->transport_document_type_id}:{$status}";$this->open($company,$key,'document_'.$status,$status==='expired'?'Documento vencido':'Documento próximo a vencer',$d->resource_name_snapshot.' — '.$d->type->name,$status==='expired'?'critical':'warning',$seen);}foreach(TransportDocumentType::forCompany($company)->where('is_active',1)->where('is_required',1)->get()as$type){foreach($this->resources($company,$type->applies_to)as$id=>$name){$exists=TransportDocument::forCompany($company)->where('transport_document_type_id',$type->id)->where('resource_type',$type->applies_to)->where('resource_id',$id)->where('is_current',1)->exists();if(!$exists){$key="transport:{$type->applies_to}:{$id}:document:{$type->id}:missing";$this->open($company,$key,'document_missing','Documento configurado faltante',$name.' — '.$type->name,'warning',$seen);}}}TransportAlert::forCompany($company)->whereIn('type',['document_expired','document_expiring','document_missing'])->where('status','open')->whereNotIn('alert_key',$seen?:['__none__'])->update(['status'=>'resolved','resolved_at'=>now()]);return count($seen);}
 private function open(int$c,string$key,string$type,string$title,string$message,string$severity,array&$seen):void{$seen[]=$key;TransportAlert::updateOrCreate(['company_id'=>$c,'alert_key'=>$key],['transport_service_id'=>null,'type'=>$type,'severity'=>$severity,'title'=>$title,'message'=>$message,'status'=>'open','last_detected_at'=>now(),'resolved_at'=>null]);}
 private function resources(int$c,string$type){if($type==='vehicle')return TransportVehicle::forCompany($c)->where('status','active')->pluck('plate','id');if(in_array($type,['driver','monitor']))return TransportPerson::forCompany($c)->with('employee')->where('status','active')->where($type==='driver'?'is_driver':'is_monitor',1)->get()->mapWithKeys(fn($p)=>[$p->id=>$p->display_name]);return collect();}
 private function resourceName(int$c,string$type,?int$id,?string$name):string{if($type==='vehicle')return TransportVehicle::forCompany($c)->findOrFail($id)->plate;if(in_array($type,['driver','monitor'])){$p=TransportPerson::forCompany($c)->findOrFail($id);abort_unless($type==='driver'?$p->is_driver:$p->is_monitor,422);return$p->display_name;}abort_if(!$name,422,'Debe indicar el nombre del recurso.');return(string)$name;}
}
