<?php
namespace App\Services;
use App\Models\{TransportAlert,TransportService,TransportSetting};
class TransportAlertService { public function __construct(private TransportServicePreparationService $preparation){} public function scan(int $company):int{$setting=TransportSetting::where('company_id',$company)->first();$hours=$setting?->upcoming_service_hours??24;$arrivalTolerance=$setting?->arrival_tolerance_minutes??10;$seen=[];
 TransportService::forCompany($company)->whereIn('status',['draft','scheduled'])->whereBetween('scheduled_start_at',[now(),now()->addHours($hours)])->with(['route','vehicle','driver','monitor','passengers'])->get()->each(function($s)use(&$seen,$company){$c=$this->preparation->checklist($s);foreach([['missing_vehicle',!$s->planned_vehicle_id,'Vehículo sin asignar','warning'],['missing_driver',!$s->planned_driver_id,'Conductor sin asignar','warning'],['capacity',!$c['capacity_ok'],'Capacidad insuficiente','critical'],['conflict',(bool)$c['conflicts'],'Conflicto de programación','critical'],['not_ready',$s->status!=='ready','Servicio próximo sin preparar','warning']]as[$type,$active,$title,$severity])if($active)$this->open($s,$type,$title,$severity,$seen);});
 TransportService::forCompany($company)->with('issues')->whereIn('status',['ready','preoperational','in_progress','arrived','interrupted'])->get()->each(function($s)use(&$seen,$arrivalTolerance){if(in_array($s->status,['ready','preoperational'])&&$s->scheduled_start_at->isPast())$this->open($s,'departure_overdue','Servicio sin salida después del horario','warning',$seen);if($s->status==='in_progress'&&now()->gt($s->scheduled_arrival_at->copy()->addMinutes($arrivalTolerance)))$this->open($s,'arrival_overdue','Llegada pendiente fuera del margen','critical',$seen);if($s->status==='arrived')$this->open($s,'closing_pending','Servicio llegado pendiente de cierre','warning',$seen);if($s->status==='interrupted')$this->open($s,'interrupted','Servicio interrumpido','critical',$seen);foreach($s->issues->where('status','open')as$i)$this->open($s,'issue-'.$i->id,'Novedad abierta: '.config('transport.issue_types.'.$i->issue_type,$i->issue_type),$i->severity==='critical'?'critical':'warning',$seen);});
 TransportAlert::forCompany($company)->where('status','open')->whereNotIn('alert_key',$seen?:['__none__'])->update(['status'=>'resolved','resolved_at'=>now()]);return count($seen);}
 private function open($s,string$type,string$title,string$severity,array&$seen):void{$key="transport-service:{$s->id}:{$type}";$seen[]=$key;TransportAlert::updateOrCreate(['company_id'=>$s->company_id,'alert_key'=>$key],['transport_service_id'=>$s->id,'type'=>$type,'severity'=>$severity,'title'=>$title,'message'=>$s->route_name_snapshot.' — '.$s->scheduled_start_at->format('d/m/Y H:i'),'status'=>'open','last_detected_at'=>now(),'resolved_at'=>null]);}
}
