@extends('layouts.app')

@section('content')
@php($employerMembers = $formation->period->members->filter(fn($member) => $member->representation_type->value === 'employer'))
@php($approvedCandidatesCount = $formation->candidates->filter(fn($candidate) => $candidate->status->value === 'approved')->count())
<div class="container-fluid mt-4">
    <a href="{{ route('committees.index') }}" class="text-secondary font-weight-bold"><i class="fa fa-arrow-left mr-1"></i> Volver a comités</a>
    <div class="d-flex justify-content-between align-items-center my-4">
        <div><h2 class="text-primary font-weight-bold">{{ $formation->committee->name }}</h2><p class="text-muted mb-0">{{ $formation->title }}</p></div>
        <div><a href="{{ route('committees.formations.edit', $formation) }}" class="btn btn-outline-primary mr-2">Editar información</a><span class="badge badge-warning px-3 py-2">{{ $formation->status->label() }}</span></div>
    </div>

    <div class="row">
        <div class="col-lg-4 mb-4"><div class="card shadow border-0 h-100"><div class="card-header bg-white font-weight-bold">Resumen normativo</div><div class="card-body small"><p><strong>Empresa:</strong> {{ $formation->committee->company->razon_social }}</p><p><strong>Trabajadores:</strong> {{ $formation->workers_count }}</p><p><strong>Figura:</strong> {{ $formation->obligation_mode }}</p><p><strong>Composición:</strong> {{ $formation->required_employer_principals }} + {{ $formation->required_worker_principals }} principales</p><p class="text-muted mb-0">{{ $formation->regulation_reference }}</p></div></div></div>
        <div class="col-lg-4 mb-4"><div class="card shadow border-0 h-100"><div class="card-header bg-white font-weight-bold">Período y convocatoria</div><div class="card-body small"><p><strong>Período:</strong> {{ $formation->period->start_date->format('d/m/Y') }} – {{ $formation->period->end_date->format('d/m/Y') }}</p><p><strong>Convocatoria:</strong> {{ $formation->call_start_date->format('d/m/Y') }} – {{ $formation->call_end_date->format('d/m/Y') }}</p><p><strong>Inscripción:</strong> {{ $formation->candidate_registration_start->format('d/m/Y H:i') }} – {{ $formation->candidate_registration_end->format('d/m/Y H:i') }}</p><p><strong>Elección prevista:</strong> {{ $formation->election_start_at->format('d/m/Y H:i') }}</p></div></div></div>
        <div class="col-lg-4 mb-4"><div class="card shadow border-0 h-100"><div class="card-header bg-white font-weight-bold">Avance</div><div class="card-body text-center"><div class="row"><div class="col"><div class="h3 text-primary">{{ $employerMembers->count() }}</div><small>Representantes</small></div><div class="col"><div class="h3 text-success">{{ $formation->candidates->reject(fn($candidate) => $candidate->status->value === 'withdrawn')->count() }}</div><small>Candidatos</small></div></div></div></div></div>
    </div>

    <div class="card shadow border-0 mb-4"><div class="card-header bg-white font-weight-bold">Elección de representantes de los trabajadores</div><div class="card-body">
        @if($formation->election)<p>Estado: <span class="badge badge-primary">{{ $formation->election->status->label() }}</span></p><a href="{{ route('committees.elections.show', $formation->election) }}" class="btn btn-primary">Gestionar elección</a>
        @else<p class="text-muted">Revise y apruebe los candidatos antes de congelar la lista y generar el censo electoral.</p><p><strong>Candidatos aprobados:</strong> <span class="badge badge-{{ $approvedCandidatesCount > 0 ? 'success' : 'danger' }}">{{ $approvedCandidatesCount }}</span></p><form method="POST" action="{{ route('committees.elections.store', $formation) }}" class="form-inline">@csrf<label class="mr-2">Máximo de selecciones por voto</label><input type="number" name="max_selections" min="1" max="{{ max(1, $approvedCandidatesCount) }}" value="1" class="form-control mr-2" required><button class="btn btn-primary" @disabled($approvedCandidatesCount === 0)>Preparar elección</button>@if($approvedCandidatesCount === 0)<small class="text-danger ml-2">Debe aprobar al menos un candidato.</small>@else<small class="text-muted ml-2">No puede superar los {{ $approvedCandidatesCount }} candidatos aprobados.</small>@endif</form>@endif
    </div></div>

    <div class="row">
        <div class="col-lg-6 mb-4"><div class="card shadow border-0"><div class="card-header bg-white d-flex justify-content-between"><strong>Representantes del empleador</strong>@if(!$formation->election)<button class="btn btn-sm btn-primary" data-toggle="modal" data-target="#addEmployerMemberModal">Adicionar representante</button>@endif</div><div class="card-body p-0"><table class="table table-hover mb-0"><thead><tr><th>Empleado</th><th>Tipo</th><th>Acciones</th></tr></thead><tbody>@forelse($employerMembers as $member)<tr><td>{{ $member->employee->nombre_completo }}</td><td>{{ $member->member_type->value === 'principal' ? 'Principal' : 'Suplente' }}</td><td>@if(!$formation->election)<button class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#editEmployerMember{{$member->id}}">Editar</button> <button class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#removeEmployerMember{{$member->id}}">Retirar</button>@endif</td></tr>@empty<tr><td colspan="3" class="text-center text-muted">Sin representantes registrados.</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="col-lg-6 mb-4"><div class="card shadow border-0"><div class="card-header bg-white d-flex justify-content-between"><strong>Candidatos</strong>@if(!$formation->election)<button class="btn btn-sm btn-primary" data-toggle="modal" data-target="#addCandidateModal">Adicionar empleado</button>@endif</div><div class="card-body p-0"><table class="table table-hover mb-0"><thead><tr><th>Empleado</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>@forelse($formation->candidates as $candidate)<tr><td>{{ $candidate->employee->nombre_completo }}</td><td><span class="badge badge-{{ $candidate->status->value === 'approved' ? 'success' : ($candidate->status->value === 'withdrawn' ? 'secondary' : 'info') }}">{{ ['approved'=>'Aprobado','registered'=>'Registrado','withdrawn'=>'Retirado','rejected'=>'Rechazado'][$candidate->status->value] ?? $candidate->status->value }}</span></td><td>@if(!$formation->election && $candidate->status->value !== 'withdrawn')@if($candidate->status->value !== 'approved')<form method="POST" action="{{ route('committees.candidates.approve', $candidate) }}" class="d-inline">@csrf<button class="btn btn-sm btn-success">Aprobar</button></form>@endif <button class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#withdrawCandidate{{$candidate->id}}">Retirar</button>@endif</td></tr>@empty<tr><td colspan="3" class="text-center text-muted">Sin candidatos registrados.</td></tr>@endforelse</tbody></table></div></div></div>
    </div>
</div>

@if(!$formation->election)
<div class="modal fade" id="addEmployerMemberModal"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('committees.members.store', $formation->period) }}">@csrf<div class="modal-header"><h5>Adicionar representante del empleador</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="form-group"><label>Empleado</label><select name="employee_id" class="form-control" required><option value="">Seleccione</option>@foreach($availableEmployerEmployees as $employee)<option value="{{$employee->id}}">{{$employee->nombre_completo}} — {{$employee->cargo}}</option>@endforeach</select></div><div class="form-group"><label>Tipo</label><select name="member_type" class="form-control" required><option value="principal">Principal</option><option value="substitute">Suplente</option></select></div><div class="form-group"><label>Fecha de designación</label><input type="date" name="designation_date" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="form-group"><label>Observaciones</label><textarea name="notes" class="form-control" maxlength="2000"></textarea></div><div class="custom-control custom-checkbox"><input type="checkbox" name="eligibility_confirmed" value="1" id="newEmployerEligibility" class="custom-control-input" required><label for="newEmployerEligibility" class="custom-control-label">Confirmo su elegibilidad</label></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button class="btn btn-primary">Adicionar</button></div></form></div></div>

@foreach($employerMembers as $member)
<div class="modal fade" id="editEmployerMember{{$member->id}}"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{ route('committees.members.update', $member) }}">@csrf @method('PUT')<div class="modal-header"><h5>Editar representante del empleador</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="form-group"><label>Empleado</label><select name="employee_id" class="form-control" required><option value="{{$member->employee_id}}">{{$member->employee->nombre_completo}} — {{$member->employee->cargo}}</option>@foreach($availableEmployerEmployees as $employee)<option value="{{$employee->id}}">{{$employee->nombre_completo}} — {{$employee->cargo}}</option>@endforeach</select></div><div class="form-group"><label>Tipo</label><select name="member_type" class="form-control" required><option value="principal" @selected($member->member_type->value === 'principal')>Principal</option><option value="substitute" @selected($member->member_type->value === 'substitute')>Suplente</option></select></div><div class="form-group"><label>Fecha de designación</label><input type="date" name="designation_date" value="{{$member->designation_date?->format('Y-m-d')}}" class="form-control" required></div><div class="form-group"><label>Observaciones</label><textarea name="notes" class="form-control" maxlength="2000">{{$member->notes}}</textarea></div><input type="hidden" name="eligibility_confirmed" value="1"></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button class="btn btn-primary">Guardar cambios</button></div></form></div></div>
<div class="modal fade" id="removeEmployerMember{{$member->id}}"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5>Retirar representante</h5></div><div class="modal-body">¿Confirma que desea retirar a <strong>{{$member->employee->nombre_completo}}</strong>?</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><form method="POST" action="{{ route('committees.members.destroy', $member) }}">@csrf @method('DELETE')<button class="btn btn-danger">Confirmar retiro</button></form></div></div></div></div>
@endforeach

<div class="modal fade" id="addCandidateModal"><div class="modal-dialog"><form class="modal-content" method="POST" enctype="multipart/form-data" action="{{route('committees.candidates.store',$formation)}}">@csrf<div class="modal-header"><h5>Adicionar candidato</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="form-group"><label>Empleado</label><select name="employee_id" class="form-control" required><option value="">Seleccione</option>@foreach($availableEmployees as $employee)<option value="{{$employee->id}}">{{$employee->nombre_completo}} — {{$employee->cargo}}</option>@endforeach</select></div><div class="form-group"><label>Fotografía</label><input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required></div><div class="form-group"><label>Perfil breve</label><textarea name="short_profile" class="form-control"></textarea></div><div class="form-group"><label>Propuesta</label><textarea name="proposal" class="form-control"></textarea></div><div class="custom-control custom-checkbox"><input type="checkbox" name="eligibility_confirmed" value="1" id="newEligibility" class="custom-control-input" required><label for="newEligibility" class="custom-control-label">Confirmo su elegibilidad</label></div></div><div class="modal-footer"><button class="btn btn-primary">Adicionar</button></div></form></div></div>
@foreach($formation->candidates as $candidate)@if($candidate->status->value !== 'withdrawn')<div class="modal fade" id="withdrawCandidate{{$candidate->id}}"><div class="modal-dialog"><form class="modal-content" method="POST" action="{{route('committees.candidates.withdraw',$candidate)}}">@csrf<div class="modal-header"><h5>Retirar a {{$candidate->employee->nombre_completo}}</h5></div><div class="modal-body"><label>Motivo del retiro</label><textarea name="reason" class="form-control" minlength="10" required></textarea><small class="text-muted">El registro se conservará para trazabilidad.</small></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button><button class="btn btn-danger">Confirmar retiro</button></div></form></div></div>@endif @endforeach
@endif
@endsection
