<?php
namespace App\Http\Requests;use Illuminate\Foundation\Http\FormRequest;
class StoreTrainingQuestionRequest extends FormRequest{
 public function authorize(){return$this->user()?->can('capacitaciones.evaluaciones.crear')??false;}
 public function needsOptions(){return in_array($this->input('question_type'),['single_choice','multiple_choice','true_false']);}
 public function rules(){$needsOptions=$this->needsOptions();return['training_topic_id'=>'required|exists:training_topics,id','question_text'=>'required|string|max:3000','question_type'=>'required|in:single_choice,multiple_choice,true_false,short_answer,long_answer','explanation'=>'nullable|string|max:3000','default_points'=>'required|numeric|min:0.01|max:1000','is_critical'=>'nullable|boolean','options'=>[$needsOptions?'required':'nullable','array'],'options.*'=>'required|string|max:1000','correct_options'=>[$needsOptions?'required':'nullable','array'],'correct_options.*'=>'integer|min:0'];}
 public function attributes(){return['training_topic_id'=>'tema','question_text'=>'pregunta','question_type'=>'tipo de pregunta','explanation'=>'explicación','default_points'=>'puntos','options'=>'opciones','options.*'=>'opción','correct_options'=>'respuesta correcta','correct_options.*'=>'respuesta correcta'];}
 public function messages(){return['correct_options.required'=>'Debe marcar al menos una respuesta correcta.','options.required'=>'Debe registrar las opciones de respuesta.'];}
 public function withValidator($validator){$validator->after(function($v){if(!$this->needsOptions())return;$options=$this->input('options',[]);$correct=array_unique($this->input('correct_options',[]));if(count($options)<2)$v->errors()->add('options','Debe registrar al menos dos opciones.');if(count($correct)<1)$v->errors()->add('correct_options','Debe marcar al menos una respuesta correcta.');$type=$this->input('question_type');if($type&&$type!=='multiple_choice'&&count($correct)>1)$v->errors()->add('correct_options','Este tipo de pregunta admite una sola respuesta correcta.');foreach($correct as$i)if(!array_key_exists($i,$options))$v->errors()->add('correct_options','La respuesta correcta seleccionada no existe entre las opciones.');});}
}
