<?php
namespace Tests\Feature;
use App\Models\{TransportChecklistTemplate,TransportPerson,TransportRoute,TransportService,TransportSetting,TransportVehicle};
use App\Services\TransportOperationService;use Illuminate\Foundation\Testing\DatabaseTransactions;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;use Tests\TestCase;
class TransportOperationRulesTest extends TestCase { use DatabaseTransactions;
 private function service():TransportService{$company=(int)DB::table('perfil_empresas')->value('id');$vehicle=TransportVehicle::create(['company_id'=>$company,'plate'=>'OP'.Str::upper(Str::random(5)),'vehicle_type'=>'van','capacity'=>20,'owner_type'=>'company','status'=>'active','created_by'=>1]);$driver=TransportPerson::create(['company_id'=>$company,'person_type'=>'external','name'=>'Conductor operacional','document_number'=>'OPD'.Str::random(8),'is_driver'=>true,'status'=>'active','created_by'=>1]);$route=TransportRoute::create(['company_id'=>$company,'code'=>'OP'.Str::random(6),'name'=>'Ruta operacional','route_type'=>'pickup','origin'=>'A','destination'=>'B','status'=>'active','created_by'=>1]);TransportSetting::updateOrCreate(['company_id'=>$company],['service_name'=>'Transporte','arrival_tolerance_minutes'=>10,'departure_tolerance_minutes'=>10,'turnaround_minutes'=>0,'upcoming_service_hours'=>24,'requires_arrival_signature'=>false,'requires_departure_odometer'=>false,'requires_arrival_odometer'=>false,'created_by'=>1]);return TransportService::create(['company_id'=>$company,'uuid'=>(string)Str::uuid(),'transport_route_id'=>$route->id,'service_date'=>'2026-08-20','service_type'=>'pickup','shift'=>'morning','scheduled_start_at'=>'2026-08-20 06:00:00','scheduled_arrival_at'=>'2026-08-20 07:00:00','planned_vehicle_id'=>$vehicle->id,'planned_driver_id'=>$driver->id,'route_name_snapshot'=>'Ruta operacional','origin_snapshot'=>'A','destination_snapshot'=>'B','status'=>'ready','passenger_snapshot_status'=>'frozen','generation_source'=>'manual','created_by'=>1]);}
 public function test_state_machine_preserves_planned_resources_and_blocks_double_departure():void{$s=$this->service();$template=TransportChecklistTemplate::create(['company_id'=>$s->company_id,'name'=>'Control configurable','blocks_on_critical_failure'=>true,'status'=>'active']);$item=$template->items()->create(['label'=>'Control definido por la empresa','sort_order'=>1,'is_critical'=>false,'is_required'=>true]);$op=app(TransportOperationService::class);$op->completePreoperational($s,['template_id'=>$template->id,'results'=>[['item_id'=>$item->id,'result'=>'compliant','observation'=>null]]],1);$op->departure($s->fresh(),['departure_odometer'=>100],1);$s->refresh();$this->assertSame('in_progress',$s->status);$this->assertSame($s->planned_vehicle_id,$s->actual_vehicle_id);$this->assertNotNull($s->actual_start_at);$this->expectException(ValidationException::class);$op->departure($s,['departure_odometer'=>101],1);}
 public function test_arrival_rejects_lower_odometer_and_closed_service_is_terminal():void{$s=$this->service();$s->update(['status'=>'in_progress','actual_vehicle_id'=>$s->planned_vehicle_id,'actual_driver_id'=>$s->planned_driver_id,'actual_start_at'=>now(),'departure_odometer'=>100]);$op=app(TransportOperationService::class);try{$op->arrival($s,['arrival_odometer'=>99],1);$this->fail('Debió rechazar el odómetro.');}catch(ValidationException){$this->assertNull($s->fresh()->actual_arrival_at);}$op->arrival($s->fresh(),['arrival_odometer'=>135,'receiver_name'=>'Responsable externo'],1);$op->close($s->fresh(),1);$this->assertSame('closed',$s->fresh()->status);$this->expectException(ValidationException::class);$op->arrival($s->fresh(),['arrival_odometer'=>136],1);}
}
