@extends('layouts.app')
@section('content')
<div class="container my-4"><a href="{{route('committees.elections.scrutiny',$election)}}" class="btn btn-outline-secondary mb-3">← Regresar al escrutinio</a><h2>Validación para conformar {{$election->formationProcess->committee->name}}</h2>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<div class="card mb-3"><div class="card-body"><h5>Checklist</h5><ul><li>✅ Elección finalizada</li><li>✅ Escrutinio e integridad validados</li><li>✅ Representantes de trabajadores definidos</li><li>✅ Representantes del empleador revisados</li><li>✅ Composición normativa recalculada</li>@foreach($preview['blockers'] as $blocker)<li class="text-danger">⚠ {{$blocker}}</li>@endforeach</ul></div></div>
<div class="row"><div class="col-md-6"><div class="card mb-3"><div class="card-header">Representantes del empleador</div><table class="table mb-0">@foreach($preview['employers'] as $member)<tr><td>{{$member->employee->nombre_completo}}</td><td>{{$member->member_type->value==='principal'?'Principal':'Suplente'}}</td></tr>@endforeach</table></div></div><div class="col-md-6"><div class="card mb-3"><div class="card-header">Representantes de trabajadores</div><table class="table mb-0">@foreach($preview['selected'] as $i=>$result)<tr><td>{{$result['name']}}</td><td>{{$i<$preview['composition']['worker_principals']?'Principal':'Suplente'}}</td><td>{{$result['votes']}} votos</td></tr>@endforeach</table></div></div></div></div>
<form id="finalizeCommitteeForm" method="POST" action="{{route('committees.formations.finalization.finalize',$election)}}">@csrf<input type="hidden" name="committee_type" value="{{$election->formationProcess->committee->type->value}}"><div class="card"><div class="card-body"><div class="form-row"><div class="form-group col-md-3"><label>Fecha de conformación</label><input type="date" name="formation_date" value="{{old('formation_date',now()->toDateString())}}" class="form-control" required></div><div class="form-group col-md-3"><label>Inicio de vigencia</label><input type="date" name="effective_from" value="{{old('effective_from',now()->toDateString())}}" class="form-control" required></div><div class="form-group col-md-3"><label>Presidente</label><select name="president_employee_id" class="form-control" required><option value="">Seleccione</option>@foreach($election->formationProcess->committee->type->value==='COPASST'?$employerOptions:$roleOptions as $option)<option value="{{$option['employee_id']}}">{{$option['name']}}</option>@endforeach</select></div><div class="form-group col-md-3"><label>Secretario</label><select name="secretary_employee_id" class="form-control" required><option value="">Seleccione</option>@foreach($roleOptions as $option)<option value="{{$option['employee_id']}}">{{$option['name']}}</option>@endforeach</select></div></div>
@if($election->formationProcess->committee->type->value==='CCL')<div class="form-row"><div class="form-group col-md-4"><label>Fecha de comunicación</label><input type="date" name="communication_date" class="form-control" required></div><div class="form-group col-md-4"><label>Referencia</label><input name="communication_reference" class="form-control"></div><div class="form-group col-md-4"><label>Notas de comunicación</label><input name="communication_notes" class="form-control"></div></div><div class="alert alert-info">Presidente y Secretario son elegidos por mutuo acuerdo entre los integrantes.</div>@endif
<button type="submit" class="btn btn-outline-danger draft-act-button" formtarget="_blank" formaction="{{route('committees.formations.finalization.draft',$election)}}" {{count($preview['blockers'])?'disabled':''}}>Generar borrador del acta</button> <button class="btn btn-success" {{count($preview['blockers'])?'disabled':''}}>Conformar comité</button></div></div></form></div>
@endsection
@section('scripts')<script>document.getElementById('finalizeCommitteeForm').addEventListener('submit',function(e){if(e.submitter&&e.submitter.classList.contains('draft-act-button'))return;e.preventDefault();var form=this;Swal.fire({title:'¿Conformar oficialmente este comité?',text:'Se consolidarán los integrantes, se generará el acta final y el comité quedará activo.',icon:'warning',showCancelButton:true,confirmButtonText:'Conformar comité',cancelButtonText:'Cancelar'}).then(function(r){if(r.isConfirmed)form.submit();});});</script>@endsection
