<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void{
 Schema::table('training_topics',function(Blueprint$t){$t->string('evaluation_method',30)->nullable();$t->decimal('default_passing_score',5,2)->nullable();$t->unsignedSmallInteger('default_maximum_attempts')->nullable();$t->boolean('requires_reinforcement_on_failure')->default(false);$t->boolean('issues_internal_certificate')->default(false);});
 Schema::table('training_sessions',function(Blueprint$t){$t->string('session_purpose',30)->default('regular')->after('training_type');});
 Schema::create('training_questions',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->restrictOnDelete();$t->foreignId('training_topic_id')->constrained()->cascadeOnDelete();$t->text('question_text');$t->string('question_type',30);$t->text('explanation')->nullable();$t->decimal('default_points',8,2)->default(1);$t->string('difficulty',20)->nullable();$t->boolean('is_critical')->default(false);$t->boolean('is_active')->default(true);$t->unsignedInteger('created_by');$t->unsignedInteger('updated_by')->nullable();$t->timestamps();});
 Schema::create('training_question_options',function(Blueprint$t){$t->id();$t->foreignId('training_question_id')->constrained()->cascadeOnDelete();$t->text('option_text');$t->boolean('is_correct')->default(false);$t->unsignedSmallInteger('sort_order')->default(0);$t->unique(['training_question_id','sort_order'],'training_question_option_sort_uq');});
 Schema::create('training_evaluations',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->restrictOnDelete();$t->foreignId('training_topic_id')->constrained()->restrictOnDelete();$t->foreignId('training_session_id')->nullable()->constrained()->cascadeOnDelete();$t->uuid('uuid')->unique();$t->string('title');$t->text('instructions');$t->string('evaluation_type',40);$t->string('evaluation_phase',20)->default('post_test');$t->decimal('passing_score',5,2);$t->unsignedSmallInteger('maximum_attempts')->nullable();$t->unsignedSmallInteger('time_limit_minutes')->nullable();$t->boolean('randomize_questions')->default(false);$t->boolean('randomize_options')->default(false);$t->boolean('show_result_immediately')->default(true);$t->boolean('show_correct_answers')->default(false);$t->boolean('requires_reinforcement')->default(false);$t->boolean('requires_confirmed_attendance')->default(true);$t->boolean('issues_internal_certificate')->default(false);$t->dateTime('opens_at')->nullable();$t->dateTime('closes_at')->nullable();$t->string('status',20)->default('draft');$t->unsignedInteger('version')->default(1);$t->dateTime('published_at')->nullable();$t->unsignedInteger('created_by');$t->unsignedInteger('updated_by')->nullable();$t->timestamps();$t->index(['company_id','status']);});
 Schema::create('training_evaluation_questions',function(Blueprint$t){$t->id();$t->foreignId('training_evaluation_id')->constrained()->cascadeOnDelete();$t->foreignId('source_question_id')->nullable()->constrained('training_questions')->nullOnDelete();$t->text('question_text');$t->string('question_type',30);$t->text('explanation')->nullable();$t->decimal('points',8,2);$t->boolean('is_critical')->default(false);$t->unsignedSmallInteger('sort_order');$t->unique(['training_evaluation_id','sort_order'],'training_eval_question_sort_uq');});
 Schema::create('training_evaluation_question_options',function(Blueprint$t){$t->id();$t->unsignedBigInteger('evaluation_question_id');$t->foreign('evaluation_question_id','training_eval_option_question_fk')->references('id')->on('training_evaluation_questions')->cascadeOnDelete();$t->text('option_text');$t->boolean('is_correct')->default(false);$t->unsignedSmallInteger('sort_order');});
 Schema::create('training_evaluation_accesses',function(Blueprint$t){$t->id();$t->foreignId('training_evaluation_id')->constrained()->cascadeOnDelete();$t->foreignId('attendance_participant_id')->constrained()->cascadeOnDelete();$t->char('token_hash',64)->unique();$t->dateTime('expires_at')->nullable();$t->dateTime('last_accessed_at')->nullable();$t->boolean('enabled')->default(true);$t->timestamps();$t->unique(['training_evaluation_id','attendance_participant_id'],'training_eval_participant_uq');});
 Schema::create('training_evaluation_attempts',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('training_evaluation_id')->constrained()->cascadeOnDelete();$t->foreignId('attendance_participant_id')->constrained()->restrictOnDelete();$t->foreignId('employee_id')->nullable()->constrained('empleados')->nullOnDelete();$t->unsignedSmallInteger('attempt_number');$t->dateTime('started_at');$t->dateTime('submitted_at')->nullable();$t->decimal('raw_score',10,2)->nullable();$t->decimal('possible_score',10,2)->nullable();$t->decimal('percentage_score',5,2)->nullable();$t->string('result',30)->nullable();$t->string('status',30)->default('started');$t->timestamps();$t->unique(['training_evaluation_id','attendance_participant_id','attempt_number'],'training_attempt_number_uq');});
 Schema::create('training_evaluation_answers',function(Blueprint$t){$t->id();$t->unsignedBigInteger('training_evaluation_attempt_id');$t->foreign('training_evaluation_attempt_id','training_answer_attempt_fk')->references('id')->on('training_evaluation_attempts')->cascadeOnDelete();$t->unsignedBigInteger('evaluation_question_id');$t->foreign('evaluation_question_id','training_answer_question_fk')->references('id')->on('training_evaluation_questions')->restrictOnDelete();$t->json('selected_option_ids')->nullable();$t->string('practical_result',30)->nullable();$t->text('evaluator_observations')->nullable();$t->decimal('points_awarded',8,2)->nullable();$t->boolean('is_correct')->nullable();$t->timestamps();$t->unique(['training_evaluation_attempt_id','evaluation_question_id'],'training_answer_question_uq');});
 Schema::create('training_reinforcements',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->restrictOnDelete();$t->foreignId('employee_id')->nullable()->constrained('empleados')->nullOnDelete();$t->foreignId('training_session_id')->constrained()->restrictOnDelete();$t->foreignId('evaluation_attempt_id')->constrained('training_evaluation_attempts')->restrictOnDelete();$t->foreignId('reinforcement_session_id')->nullable()->constrained('training_sessions')->nullOnDelete();$t->text('reason');$t->string('status',30)->default('pending');$t->dateTime('assigned_at');$t->dateTime('due_at')->nullable();$t->dateTime('completed_at')->nullable();$t->text('waiver_reason')->nullable();$t->unsignedInteger('created_by');$t->unsignedInteger('updated_by')->nullable();$t->timestamps();$t->unique('evaluation_attempt_id');});
 Schema::create('employee_training_credentials',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->restrictOnDelete();$t->foreignId('employee_id')->constrained('empleados')->restrictOnDelete();$t->foreignId('training_topic_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('training_session_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('evaluation_attempt_id')->nullable()->constrained('training_evaluation_attempts')->nullOnDelete();$t->string('credential_type',40);$t->string('name');$t->string('issuing_organization');$t->string('certificate_number')->nullable();$t->date('issued_at');$t->date('expires_at')->nullable();$t->string('document_path')->nullable();$t->string('verification_url')->nullable();$t->char('verification_code',64)->unique();$t->string('status',20)->default('valid');$t->unsignedInteger('created_by');$t->timestamps();$t->unique(['training_session_id','employee_id','credential_type'],'training_credential_session_employee_uq');});
 Schema::create('training_requirements',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->restrictOnDelete();$t->foreignId('training_topic_id')->constrained()->restrictOnDelete();$t->string('requirement_type',30);$t->string('requirement_reference')->nullable();$t->boolean('required')->default(true);$t->unsignedInteger('validity_months')->nullable();$t->boolean('requires_evaluation')->default(false);$t->boolean('requires_certificate')->default(false);$t->string('priority',20)->default('medium');$t->text('regulation_reference')->nullable();$t->boolean('is_active')->default(true);$t->unsignedInteger('created_by');$t->unsignedInteger('updated_by')->nullable();$t->timestamps();$t->index(['company_id','requirement_type','requirement_reference'],'training_requirement_resolver_idx');});
 }
 public function down():void{foreach(['training_requirements','employee_training_credentials','training_reinforcements','training_evaluation_answers','training_evaluation_attempts','training_evaluation_accesses','training_evaluation_question_options','training_evaluation_questions','training_evaluations','training_question_options','training_questions'] as$t)Schema::dropIfExists($t);Schema::table('training_sessions',fn(Blueprint$t)=>$t->dropColumn('session_purpose'));Schema::table('training_topics',fn(Blueprint$t)=>$t->dropColumn(['evaluation_method','default_passing_score','default_maximum_attempts','requires_reinforcement_on_failure','issues_internal_certificate']));}
};
