<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void{
 Schema::create('transport_document_types',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->cascadeOnDelete();$t->string('name');$t->string('applies_to',20);$t->boolean('is_required')->default(false);$t->boolean('requires_number')->default(false);$t->boolean('requires_issue_date')->default(false);$t->boolean('requires_expiration_date')->default(false);$t->boolean('requires_file')->default(true);$t->unsignedSmallInteger('warning_days')->default(30);$t->boolean('block_operation_when_expired')->default(false);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['company_id','name','applies_to'],'tr_doc_type_unique');});
 Schema::create('transport_documents',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->cascadeOnDelete();$t->foreignId('transport_document_type_id')->constrained()->restrictOnDelete();$t->string('resource_type',20);$t->unsignedBigInteger('resource_id')->nullable();$t->string('resource_name_snapshot');$t->string('document_number')->nullable();$t->date('issued_at')->nullable();$t->date('expires_at')->nullable();$t->string('file_path')->nullable();$t->string('file_hash',64)->nullable();$t->string('original_name')->nullable();$t->string('mime_type',100)->nullable();$t->text('notes')->nullable();$t->foreignId('supersedes_document_id')->nullable()->constrained('transport_documents')->nullOnDelete();$t->boolean('is_current')->default(true);$t->unsignedBigInteger('created_by');$t->unsignedBigInteger('updated_by')->nullable();$t->timestamps();$t->index(['company_id','resource_type','resource_id'],'tr_doc_resource_idx');$t->index(['company_id','expires_at','is_current'],'tr_doc_expiry_idx');});
 Schema::table('transport_alerts',function(Blueprint$t){$t->dateTime('acknowledged_at')->nullable();$t->unsignedBigInteger('acknowledged_by')->nullable();$t->dateTime('dismissed_at')->nullable();$t->unsignedBigInteger('dismissed_by')->nullable();});
 Schema::table('transport_services',function(Blueprint$t){$t->index(['company_id','service_date','transport_route_id'],'tr_service_route_period_idx');$t->index(['company_id','service_date','actual_vehicle_id'],'tr_service_vehicle_period_idx');$t->index(['company_id','service_date','actual_driver_id'],'tr_service_driver_period_idx');});
 Schema::table('transport_service_issues',function(Blueprint$t){$t->index(['company_id','occurred_at','issue_type'],'tr_issue_period_type_idx');});
 }
 public function down():void{Schema::table('transport_service_issues',fn(Blueprint$t)=>$t->dropIndex('tr_issue_period_type_idx'));Schema::table('transport_services',function(Blueprint$t){$t->dropIndex('tr_service_route_period_idx');$t->dropIndex('tr_service_vehicle_period_idx');$t->dropIndex('tr_service_driver_period_idx');});Schema::table('transport_alerts',fn(Blueprint$t)=>$t->dropColumn(['acknowledged_at','acknowledged_by','dismissed_at','dismissed_by']));Schema::dropIfExists('transport_documents');Schema::dropIfExists('transport_document_types');}
};
