<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\{DB,Schema};return new class extends Migration{public function up():void{
 if(!Schema::hasColumn('matriz_riesgos','company_id')){Schema::table('matriz_riesgos',fn(Blueprint $t)=>$t->foreignId('company_id')->nullable()->after('id')->constrained('perfil_empresas')->nullOnDelete());if($id=DB::table('perfil_empresas')->value('id'))DB::table('matriz_riesgos')->whereNull('company_id')->update(['company_id'=>$id]);}
 Schema::create('training_needs',function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->cascadeOnDelete();$t->string('code');$t->string('title');$t->text('description');$t->string('origin_type',50);$t->text('origin_description')->nullable();$t->string('priority',20);$t->date('identified_at');$t->date('required_by')->nullable();$t->string('target_population_type',40);$t->text('target_population_description');$t->string('status',20)->default('identified');$t->foreignId('identified_by')->nullable()->constrained('empleados')->nullOnDelete();$t->unsignedInteger('created_by');$t->unsignedInteger('updated_by')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['company_id','code']);});
 Schema::create('training_need_risk',function(Blueprint $t){$t->foreignId('training_need_id')->constrained()->cascadeOnDelete();$t->foreignId('matriz_riesgo_id')->constrained('matriz_riesgos')->cascadeOnDelete();$t->primary(['training_need_id','matriz_riesgo_id'],'training_need_risk_pk');});
 Schema::create('training_topics',function(Blueprint $t){$t->id();$t->foreignId('company_id')->nullable()->constrained('perfil_empresas')->cascadeOnDelete();$t->string('code');$t->string('name');$t->text('description');$t->string('training_type',30);$t->text('general_objective');$t->text('specific_objectives')->nullable();$t->text('contents')->nullable();$t->unsignedInteger('suggested_duration_minutes')->nullable();$t->string('suggested_modality',20)->nullable();$t->boolean('requires_evaluation_default')->default(false);$t->boolean('is_regulated')->default(false);$t->text('regulation_reference')->nullable();$t->boolean('is_active')->default(true);$t->unsignedInteger('created_by');$t->unsignedInteger('updated_by')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['company_id','code']);});
 Schema::create('training_programs',function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->cascadeOnDelete();$t->unsignedSmallInteger('year');$t->unsignedInteger('version')->default(1);$t->string('title');$t->text('general_objective');$t->text('specific_objectives')->nullable();$t->text('scope');$t->date('starts_at');$t->date('ends_at');$t->string('status',20)->default('draft');$t->foreignId('prepared_by')->nullable()->constrained('empleados')->nullOnDelete();$t->dateTime('prepared_at')->nullable();$t->dateTime('reviewed_at')->nullable();$t->dateTime('approved_at')->nullable();$t->unsignedInteger('approved_by')->nullable();$t->text('approval_justification')->nullable();$t->unsignedInteger('created_by');$t->unsignedInteger('updated_by')->nullable();$t->timestamps();$t->unique(['company_id','year','version']);});
 Schema::create('training_program_items',function(Blueprint $t){$t->id();$t->foreignId('training_program_id')->constrained()->cascadeOnDelete();$t->foreignId('training_topic_id')->nullable()->constrained()->nullOnDelete();$t->string('title');$t->text('description')->nullable();$t->string('training_type',30);$t->unsignedTinyInteger('planned_month');$t->date('planned_date')->nullable();$t->string('target_population_type',40);$t->text('target_population_description');$t->foreignId('responsible_employee_id')->nullable()->constrained('empleados')->nullOnDelete();$t->string('external_responsible')->nullable();$t->unsignedInteger('estimated_duration_minutes')->nullable();$t->string('planned_modality',20);$t->string('priority',20);$t->string('status',30)->default('planned');$t->foreignId('annual_work_plan_item_id')->nullable()->constrained('actividades_plan')->nullOnDelete();$t->timestamps();});
 Schema::create('training_need_program_item',function(Blueprint $t){$t->foreignId('training_need_id')->constrained()->cascadeOnDelete();$t->foreignId('training_program_item_id')->constrained()->cascadeOnDelete();$t->primary(['training_need_id','training_program_item_id'],'training_need_item_pk');});
 Schema::create('training_program_reviews',function(Blueprint $t){$t->id();$t->foreignId('training_program_id')->constrained()->cascadeOnDelete();$t->date('review_date');$t->string('review_type',30);$t->foreignId('committee_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('committee_meeting_id')->nullable()->constrained()->nullOnDelete();$t->boolean('copasst_or_vigia_participation');$t->foreignId('senior_management_employee_id')->nullable()->constrained('empleados')->nullOnDelete();$t->boolean('senior_management_participation');$t->text('conclusions');$t->text('improvement_actions');$t->string('document_path')->nullable();$t->unsignedInteger('reviewed_by');$t->timestamps();});
 Schema::create('training_audits',function(Blueprint $t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->cascadeOnDelete();$t->string('event',60);$t->string('subject_type',40);$t->unsignedBigInteger('subject_id');$t->unsignedInteger('user_id')->nullable();$t->json('metadata')->nullable();$t->timestamp('created_at')->useCurrent();});
 }public function down():void{foreach(['training_audits','training_program_reviews','training_need_program_item','training_program_items','training_programs','training_topics','training_need_risk','training_needs']as$t)Schema::dropIfExists($t);if(Schema::hasColumn('matriz_riesgos','company_id'))Schema::table('matriz_riesgos',fn(Blueprint $t)=>$t->dropConstrainedForeignId('company_id'));}};
