<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::table('transport_settings',function(Blueprint$t){$t->unsignedSmallInteger('turnaround_minutes')->default(0)->after('arrival_tolerance_minutes');$t->unsignedSmallInteger('upcoming_service_hours')->default(24)->after('turnaround_minutes');});
 Schema::create('transport_schedules',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->cascadeOnDelete();$t->foreignId('transport_route_id')->constrained()->restrictOnDelete();$t->string('name');$t->date('starts_on');$t->date('ends_on');$t->time('default_start_time');$t->time('default_arrival_time');$t->boolean('arrival_next_day')->default(false);$t->string('service_type',20);$t->string('shift',20);$t->foreignId('vehicle_id')->nullable()->constrained('transport_vehicles')->nullOnDelete();$t->foreignId('driver_id')->nullable()->constrained('transport_personnel')->nullOnDelete();$t->foreignId('monitor_id')->nullable()->constrained('transport_personnel')->nullOnDelete();$t->string('status',20)->default('active');$t->unsignedBigInteger('created_by');$t->unsignedBigInteger('updated_by')->nullable();$t->timestamps();});
 Schema::create('transport_schedule_days',function(Blueprint$t){$t->id();$t->foreignId('transport_schedule_id')->constrained()->cascadeOnDelete();$t->unsignedTinyInteger('day_of_week');$t->unique(['transport_schedule_id','day_of_week']);});
 Schema::create('transport_calendar_exceptions',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->cascadeOnDelete();$t->foreignId('transport_route_id')->nullable()->constrained()->cascadeOnDelete();$t->date('exception_date');$t->string('type',30);$t->string('reason');$t->boolean('applies_to_all_routes')->default(false);$t->unsignedBigInteger('created_by');$t->timestamps();$t->unique(['company_id','transport_route_id','exception_date'],'transport_calendar_exception_unique');});
 Schema::create('transport_services',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->cascadeOnDelete();$t->uuid('uuid')->unique();$t->foreignId('transport_route_id')->constrained()->restrictOnDelete();$t->foreignId('transport_schedule_id')->nullable()->constrained()->nullOnDelete();$t->date('service_date');$t->string('service_type',20);$t->string('shift',20);$t->dateTime('scheduled_start_at');$t->dateTime('scheduled_arrival_at');$t->foreignId('planned_vehicle_id')->nullable()->constrained('transport_vehicles')->nullOnDelete();$t->foreignId('planned_driver_id')->nullable()->constrained('transport_personnel')->nullOnDelete();$t->foreignId('planned_monitor_id')->nullable()->constrained('transport_personnel')->nullOnDelete();$t->string('route_name_snapshot');$t->string('origin_snapshot');$t->string('destination_snapshot');$t->string('status',20)->default('draft');$t->string('passenger_snapshot_status',20)->default('pending');$t->string('generation_source',30)->default('manual');$t->text('notes')->nullable();$t->text('cancellation_reason')->nullable();$t->dateTime('cancelled_at')->nullable();$t->unsignedBigInteger('cancelled_by')->nullable();$t->unsignedBigInteger('created_by');$t->unsignedBigInteger('updated_by')->nullable();$t->timestamps();$t->unique(['company_id','transport_route_id','scheduled_start_at','service_type','shift'],'transport_service_unique');$t->index(['company_id','service_date','status']);});
 Schema::create('transport_service_passengers',function(Blueprint$t){$t->id();$t->foreignId('transport_service_id')->constrained()->cascadeOnDelete();$t->foreignId('transport_passenger_id')->constrained()->restrictOnDelete();$t->foreignId('transport_route_stop_id')->nullable()->constrained()->nullOnDelete();$t->string('passenger_name_snapshot');$t->string('group_snapshot')->nullable();$t->boolean('expected')->default(true);$t->string('status',20)->default('expected');$t->boolean('added_manually')->default(false);$t->text('added_reason')->nullable();$t->unsignedBigInteger('added_by')->nullable();$t->text('excluded_reason')->nullable();$t->unsignedBigInteger('excluded_by')->nullable();$t->dateTime('excluded_at')->nullable();$t->timestamps();$t->unique(['transport_service_id','transport_passenger_id'],'transport_service_passenger_unique');});
 Schema::create('transport_service_changes',function(Blueprint$t){$t->id();$t->foreignId('transport_service_id')->constrained()->cascadeOnDelete();$t->string('change_type',30);$t->json('old_data')->nullable();$t->json('new_data')->nullable();$t->text('reason');$t->unsignedBigInteger('changed_by');$t->timestamp('changed_at')->useCurrent();});
 Schema::create('transport_alerts',function(Blueprint$t){$t->id();$t->foreignId('company_id')->constrained('perfil_empresas')->cascadeOnDelete();$t->foreignId('transport_service_id')->nullable()->constrained()->cascadeOnDelete();$t->string('alert_key');$t->string('type',40);$t->string('severity',20);$t->string('title');$t->text('message');$t->string('status',20)->default('open');$t->dateTime('last_detected_at');$t->dateTime('resolved_at')->nullable();$t->timestamps();$t->unique(['company_id','alert_key']);});
 }
 public function down():void{foreach(['transport_alerts','transport_service_changes','transport_service_passengers','transport_services','transport_calendar_exceptions','transport_schedule_days','transport_schedules']as$t)Schema::dropIfExists($t);Schema::table('transport_settings',fn(Blueprint$t)=>$t->dropColumn(['turnaround_minutes','upcoming_service_hours']));}};
