<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up(): void {
  Schema::create('committee_elections', function(Blueprint $t){$t->id();$t->uuid('public_uuid')->unique();$t->foreignId('formation_process_id')->constrained('committee_formation_processes')->cascadeOnDelete();$t->string('status',30)->default('draft');$t->dateTime('opens_at');$t->dateTime('closes_at');$t->unsignedTinyInteger('max_selections');$t->unsignedInteger('electorate_count')->default(0);$t->unsignedInteger('candidate_count')->default(0);$t->dateTime('opened_at')->nullable();$t->dateTime('closed_at')->nullable();$t->dateTime('scrutinized_at')->nullable();$t->dateTime('results_validated_at')->nullable();$t->dateTime('annulled_at')->nullable();$t->unsignedInteger('annulled_by')->nullable();$t->text('annulment_reason')->nullable();$t->char('result_integrity_hash',64)->nullable();$t->unsignedInteger('created_by')->nullable();$t->unsignedInteger('updated_by')->nullable();$t->timestamps();$t->unique('formation_process_id');$t->foreign('created_by')->references('id')->on('users')->nullOnDelete();$t->foreign('updated_by')->references('id')->on('users')->nullOnDelete();$t->foreign('annulled_by')->references('id')->on('users')->nullOnDelete();});
  Schema::create('committee_election_candidates', function(Blueprint $t){$t->id();$t->foreignId('election_id')->constrained('committee_elections')->cascadeOnDelete();$t->foreignId('committee_candidate_id')->constrained('committee_candidates')->restrictOnDelete();$t->string('name');$t->string('position')->nullable();$t->string('department')->nullable();$t->string('photo_path');$t->text('short_profile')->nullable();$t->text('proposal')->nullable();$t->boolean('enabled')->default(true);$t->unique(['election_id','committee_candidate_id'],'election_candidate_unique');});
  Schema::create('committee_election_voters', function(Blueprint $t){$t->id();$t->foreignId('election_id')->constrained('committee_elections')->cascadeOnDelete();$t->foreignId('employee_id')->constrained('empleados')->restrictOnDelete();$t->string('status',20)->default('enabled');$t->boolean('has_voted')->default(false);$t->dateTime('voted_at')->nullable();$t->char('credential_hash',64)->unique();$t->dateTime('credential_expires_at');$t->dateTime('credential_used_at')->nullable();$t->timestamps();$t->unique(['election_id','employee_id'],'election_voter_unique');});
  Schema::create('committee_ballots', function(Blueprint $t){$t->uuid('uuid')->primary();$t->foreignId('election_id')->constrained('committee_elections')->restrictOnDelete();$t->char('integrity_hash',64);});
  Schema::create('committee_ballot_selections', function(Blueprint $t){$t->id();$t->uuid('ballot_uuid');$t->foreignId('election_candidate_id')->constrained('committee_election_candidates')->restrictOnDelete();$t->foreign('ballot_uuid')->references('uuid')->on('committee_ballots')->cascadeOnDelete();$t->unique(['ballot_uuid','election_candidate_id'],'ballot_selection_unique');});
  Schema::create('committee_election_ties', function(Blueprint $t){$t->id();$t->foreignId('election_id')->constrained('committee_elections')->cascadeOnDelete();$t->json('candidate_ids');$t->unsignedInteger('votes');$t->unsignedTinyInteger('affected_positions');$t->string('status',20)->default('pending');$t->text('resolution_method')->nullable();$t->text('observations')->nullable();$t->unsignedInteger('resolved_by')->nullable();$t->dateTime('resolved_at')->nullable();$t->timestamps();$t->foreign('resolved_by')->references('id')->on('users')->nullOnDelete();});
  Schema::create('committee_election_audits', function(Blueprint $t){$t->id();$t->foreignId('election_id')->constrained('committee_elections')->cascadeOnDelete();$t->string('event',50);$t->unsignedInteger('user_id')->nullable();$t->json('metadata')->nullable();$t->timestamp('created_at')->useCurrent();$t->foreign('user_id')->references('id')->on('users')->nullOnDelete();$t->index(['election_id','event']);});
 }
 public function down(): void {foreach(['committee_election_audits','committee_election_ties','committee_ballot_selections','committee_ballots','committee_election_voters','committee_election_candidates','committee_elections'] as $table)Schema::dropIfExists($table);}
};
