<?php
return [
 'need_origins'=>['risk_matrix'=>'Matriz de riesgos','minimum_standards'=>'Estándares mínimos','incident'=>'Incidente','accident'=>'Accidente','inspection'=>'Inspección','audit'=>'Auditoría','copasst'=>'COPASST','labor_coexistence_committee'=>'Comité de Convivencia','annual_work_plan'=>'Plan Anual de Trabajo','regulation'=>'Normativa','management'=>'Dirección','employee_request'=>'Solicitud del trabajador','process_change'=>'Cambio de proceso','equipment_change'=>'Cambio de equipo','job_change'=>'Cambio de cargo','other'=>'Otro'],
 'training_types'=>['training'=>'Capacitación','induction'=>'Inducción','reinduction'=>'Reinducción','workshop'=>'Taller','training_practice'=>'Entrenamiento','talk'=>'Charla','awareness'=>'Sensibilización','simulation'=>'Simulacro','socialization'=>'Socialización','other'=>'Otro'],
 'population_types'=>['all_workers'=>'Todos los trabajadores','area'=>'Área','job'=>'Cargo','risk_exposure'=>'Exposición a riesgo','specific_group'=>'Grupo específico','specific_employees'=>'Empleados específicos','contractors'=>'Contratistas','other'=>'Otro'],
 'modalities'=>['presential'=>'Presencial','virtual'=>'Virtual','hybrid'=>'Híbrida','to_define'=>'Por definir'],
 'priority_labels'=>['low'=>'Baja','medium'=>'Media','high'=>'Alta','critical'=>'Crítica'],
 'need_status_labels'=>['identified'=>'Identificada','evaluated'=>'Evaluada','approved'=>'Aprobada','planned'=>'Programada','attended'=>'Atendida','cancelled'=>'Cancelada'],
 'program_status_labels'=>['draft'=>'Borrador','in_review'=>'En revisión','approved'=>'Aprobado','active'=>'Activo','closed'=>'Cerrado','cancelled'=>'Cancelado'],
 'program_item_status_labels'=>['planned'=>'Pendiente','scheduled'=>'Programada','partially_executed'=>'Ejecutada parcialmente','executed'=>'Ejecutada','reprogrammed'=>'Reprogramada','cancelled_justified'=>'Cancelada con justificación'],
 'session_status_labels'=>['draft'=>'Borrador','scheduled'=>'Programada','called'=>'Convocada','attendance_open'=>'Asistencia abierta','in_progress'=>'En ejecución','completed'=>'Finalizada','closed'=>'Cerrada','cancelled'=>'Cancelada','rescheduled'=>'Reprogramada'],
 'invitation_status_labels'=>['pending'=>'Pendiente','sent'=>'Enviada','delivered'=>'Entregada','failed'=>'Fallida','cancelled'=>'Cancelada','excluded'=>'Excluida'],
 'attendance_status_labels'=>['pending'=>'Pendiente','confirmed'=>'Confirmada','absent'=>'Ausente','excused'=>'Excusada','voided'=>'Anulada'],
 'closure_checklist_labels'=>['execution_completed'=>'Ejecución finalizada','instructor'=>'Instructor definido','duration'=>'Duración registrada','attendance'=>'Asistencia cerrada','material'=>'Material cargado','execution_report'=>'Informe de ejecución cargado'],
 'evidence_type_labels'=>['training_material'=>'Material de capacitación','photo'=>'Fotografía','execution_report'=>'Informe de ejecución','instructor_document'=>'Documento del instructor','external_certificate'=>'Certificado externo','other'=>'Otro'],
 'question_types'=>['single_choice'=>'Selección única','multiple_choice'=>'Selección múltiple','true_false'=>'Verdadero/falso','short_answer'=>'Respuesta corta','long_answer'=>'Respuesta larga'],
 'evaluation_attempt_status_labels'=>['started'=>'En curso','graded'=>'Calificada','pending_review'=>'Pendiente de revisión'],
 'evaluation_status_labels'=>['draft'=>'Borrador','published'=>'Publicada','open'=>'Abierta','closed'=>'Cerrada'],
 'attendance_open_minutes'=>30,
 'attendance_close_minutes'=>30,
 'early_start_margin_minutes'=>30,
 'reminder_minutes'=>[1440,120],
 'evidence_disk'=>env('TRAINING_EVIDENCE_DISK','local'),
 'analytics_cache_minutes'=>env('TRAINING_ANALYTICS_CACHE_MINUTES',15),
 'alert_windows'=>['credential_expiration_days'=>[90,60,30,15,7],'overdue_activity_days'=>1,'pending_induction_days'=>1,'stale_session_hours'=>24,'reinforcement_overdue_days'=>1],
 'indicator_defaults'=>[
  'program_execution'=>['target'=>90,'warning'=>75,'critical'=>50],
  'coverage'=>['target'=>95,'warning'=>80,'critical'=>60],
  'evaluation'=>['target'=>90,'warning'=>75,'critical'=>50],
  'approval'=>['target'=>90,'warning'=>75,'critical'=>50],
  'reinforcement'=>['target'=>90,'warning'=>75,'critical'=>50],
  'needs_attended'=>['target'=>90,'warning'=>75,'critical'=>50],
 ],
 'legal_reference'=>'Decreto 1072 de 2015, artículos 2.2.4.6.11 a 2.2.4.6.13; Resolución 0312 de 2019; Ley 1562 de 2012.',
];
