<?php
namespace App\Http\Controllers;use App\Http\Requests\StoreAttendanceEventRequest;use App\Models\{AttendanceEvent,AttendanceParticipant,CommitteeMeeting};use App\Services\AttendanceEventService;use Endroid\QrCode\QrCode;use Endroid\QrCode\Writer\SvgWriter;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;
class AttendanceEventController extends Controller{
 public function __construct(){$this->middleware(function($request,$next){$subject=$request->route('event')??$request->route('record')??$request->route('evidence')??$request->route('meeting');$companyId=$subject instanceof AttendanceEvent?$subject->company_id:($subject instanceof \App\Models\AttendanceRecord?$subject->event->company_id:($subject instanceof \App\Models\AttendanceEvidence?$subject->event->company_id:($subject instanceof CommitteeMeeting?$subject->committee->perfil_empresa_id:null)));abort_unless($companyId&&(int)$request->user()->company_id===(int)$companyId,403,'No puede acceder a información de otra empresa.');return$next($request);});}
 public function store(CommitteeMeeting $meeting,StoreAttendanceEventRequest $request,AttendanceEventService $service){$result=$service->createFromMeeting($meeting,$request->validated(),$request->user()->id);return redirect()->route('attendance.show',$result['event'])->with(['success'=>'Asistencia digital habilitada. Guarde los códigos personales; no se mostrarán nuevamente.','attendance_token'=>$result['token'],'participant_codes'=>$result['codes']]);}
 public function show(AttendanceEvent $event,Request $request){$event->load(['company','attendable','participants.record.signature','evidences']);$token=session('attendance_token');$publicAttendanceUrl=null;$qrDataUri=null;if($token&&hash_equals((string)$event->access_token_hash,hash('sha256',$token))){$publicAttendanceUrl=$request->getSchemeAndHttpHost().$request->getBaseUrl().'/asistencia/'.$event->uuid.'/'.rawurlencode($token);$svg=(new SvgWriter)->write(new QrCode($publicAttendanceUrl))->getString();$qrDataUri='data:image/svg+xml;base64,'.base64_encode($svg);}$backUrl=route('home');$backLabel='Volver al menú';if($event->attendable instanceof \App\Models\TrainingSession){$backUrl=route('training.sessions.show',$event->attendable);$backLabel='Volver a la sesión';}elseif($event->attendable instanceof CommitteeMeeting){$backUrl=route('committees.meetings.show',$event->attendable);$backLabel='Volver a la reunión';}return view('attendance.admin.show',compact('event','publicAttendanceUrl','qrDataUri','backUrl','backLabel'));}
 public function rotate(AttendanceEvent $event,Request $request,AttendanceEventService $service){$token=$service->rotate($event,$request->user()->id);return back()->with(['success'=>'QR regenerado. El enlace anterior quedó invalidado.','attendance_token'=>$token]);}
 public function open(AttendanceEvent $event,Request $r,AttendanceEventService $s){$s->open($event,$r->user()->id);return back()->with('success','Asistencia abierta.');}
 public function close(AttendanceEvent $event,Request $r,AttendanceEventService $s){$s->close($event,$r->user()->id);return back()->with('success','Asistencia cerrada.');}
 public function finalize(AttendanceEvent $event,Request $r,AttendanceEventService $s){$s->finalize($event,$r->user()->id);return back()->with('success','Asistencia finalizada y congelada.');}
 public function qr(AttendanceEvent $event,Request $request){$token=$request->query('token',session('attendance_token'));abort_unless($token&&hash_equals($event->access_token_hash,hash('sha256',$token)),403);$url=route('attendance.public.show',['event'=>$event,'token'=>$token]);$svg=(new SvgWriter)->write(new QrCode($url))->getString();return response($svg,200,['Content-Type'=>'image/svg+xml','Content-Disposition'=>'inline; filename="asistencia-'.$event->uuid.'.svg"','Cache-Control'=>'private, no-store, no-cache, must-revalidate']);}
 public function addParticipant(AttendanceEvent $event,Request $request,AttendanceEventService $service){$data=$request->validate(['participant_type'=>'required|in:employee,external','employee_id'=>'nullable|required_if:participant_type,employee|exists:empleados,id','name'=>'nullable|required_if:participant_type,external|string|max:255','organization'=>'nullable|string|max:255','email'=>'nullable|email|max:255']);$code=strtoupper(Str::random(10));if($data['participant_type']==='employee'){$employee=\App\Models\Empleado::where('company_id',$event->company_id)->findOrFail($data['employee_id']);$name=$employee->nombre_completo;$role=$employee->cargo;$department=$employee->area_departamento;}else{$name=$data['name'];$role='Invitado externo';$department=null;}$p=$event->participants()->create(['uuid'=>(string)Str::uuid(),'participant_type'=>$data['participant_type'],'employee_id'=>$data['employee_id']??null,'name_snapshot'=>$name,'role_snapshot'=>$role,'department_snapshot'=>$department,'organization'=>$data['organization']??null,'email'=>$data['email']??null,'expected'=>true,'credential_hash'=>hash('sha256',$code),'credential_expires_at'=>$event->attendance_closes_at]);$service->audit($event,'participant_added',$request->user()->id,['participant_id'=>$p->id]);return back()->with(['success'=>'Participante agregado. Guarde su código personal.','participant_codes'=>[['name'=>$name,'code'=>$code]]]);}
 public function signature(\App\Models\AttendanceRecord $record){abort_unless($record->signature,404);return Storage::disk(config('attendance.disk'))->response($record->signature->file_path,null,['Content-Type'=>'image/png','Cache-Control'=>'private, no-store']);}
 public function manual(AttendanceEvent $event,Request $request,AttendanceEventService $service){$data=$request->validate(['participant_id'=>'required|exists:attendance_participants,id','reason'=>'required|string|min:10|max:1000','confirmed_at'=>'required|date']);$participant=$event->participants()->findOrFail($data['participant_id']);abort_if($participant->record()->exists(),422,'La persona ya tiene un registro de asistencia.');$record=$event->records()->create(['uuid'=>(string)Str::uuid(),'attendance_participant_id'=>$participant->id,'status'=>'confirmed','checked_in_at'=>$data['confirmed_at'],'confirmed_at'=>$data['confirmed_at'],'verification_method'=>'manual','verification_level'=>'basic','verification_code'=>strtoupper(Str::random(24)),'manual_reason'=>$data['reason'],'created_by'=>$request->user()->id]);$service->audit($event,'manual_attendance_created',$request->user()->id,['record_id'=>$record->id,'reason'=>$data['reason']]);return back()->with('success','Asistencia manual registrada con trazabilidad.');}
 public function voidRecord(\App\Models\AttendanceRecord $record,Request $request,AttendanceEventService $service){$data=$request->validate(['reason'=>'required|string|min:10|max:1000']);abort_if($record->status==='voided',422,'La asistencia ya fue anulada.');$record->update(['status'=>'voided','voided_at'=>now(),'voided_by'=>$request->user()->id,'void_reason'=>$data['reason']]);$service->audit($record->event,'attendance_voided',$request->user()->id,['record_id'=>$record->id,'reason'=>$data['reason']]);return back()->with('success','Registro anulado sin eliminar su historial.');}
 public function generateEvidence(AttendanceEvent $event,Request $request,\App\Services\AttendanceEvidenceService $service){abort_unless(in_array($event->status,['closed','finalized']),422,'Debe cerrar la asistencia antes de generar la evidencia.');$service->generate($event,$request->user()->id);return back()->with('success','Evidencia PDF privada generada.');}
 public function downloadEvidence(\App\Models\AttendanceEvidence $evidence){abort_unless(Storage::disk(config('attendance.disk'))->exists($evidence->file_path),404);return Storage::disk(config('attendance.disk'))->download($evidence->file_path);}
 public function export(AttendanceEvent $event){return \Maatwebsite\Excel\Facades\Excel::download(new \App\Exports\AttendanceExport($event),'asistencia-'.$event->uuid.'.xlsx');}
}
