<?php
namespace App\Http\Controllers;
use App\Http\Requests\{FinalizeCommitteeFormationRequest,GenerateFormationActRequest};use App\Models\{CommitteeElection,CommitteeFormation};use App\Services\CommitteeFormationFinalizationService;use Illuminate\Support\Facades\Storage;use Barryvdh\DomPDF\Facade\Pdf;use Carbon\Carbon;
class CommitteeFinalizationController extends Controller {
 public function show(CommitteeElection $election,CommitteeFormationFinalizationService $service){if($formation=$election->finalFormation()->with(['period.members.employee','period.roles.member.employee','committee'])->first())return view('committees.finalization.active',compact('formation'));$preview=$service->preview($election);$election->load('candidates.sourceCandidate.employee');$workerOptions=$election->candidates->whereIn('id',$preview['selected']->pluck('id'))->map(fn($candidate)=>['employee_id'=>$candidate->sourceCandidate->employee_id,'name'=>$candidate->name,'representation'=>'worker']);$employerOptions=$preview['employers']->map(fn($member)=>['employee_id'=>$member->employee_id,'name'=>$member->employee->nombre_completo,'representation'=>'employer']);$roleOptions=$employerOptions->concat($workerOptions);return view('committees.finalization.show',compact('election','preview','roleOptions','employerOptions'));}
 public function finalize(FinalizeCommitteeFormationRequest $request,CommitteeElection $election,CommitteeFormationFinalizationService $service){$formation=$service->finalize($election,$request->validated(),$request->user()->id);return redirect()->route('committees.formations.finalization.show',$election)->with('success','El comité fue conformado y activado correctamente.');}
 public function draft(GenerateFormationActRequest $request,CommitteeElection $election,CommitteeFormationFinalizationService $service){$preview=$service->preview($election);if($preview['blockers'])return back()->withErrors(['formation'=>$preview['blockers']])->withInput();$data=$request->validated();$election->load(['formationProcess.committee.company','formationProcess.period.members.employee','candidates.sourceCandidate.employee']);$effectiveFrom=Carbon::parse($data['effective_from']);$effectiveTo=$effectiveFrom->copy()->addYears($preview['composition']['period_years'])->subDay();return Pdf::loadView('pdf.committee_formation_draft',compact('election','preview','data','effectiveFrom','effectiveTo'))->stream('Borrador_Acta_Conformacion.pdf');}
 public function act(CommitteeFormation $formation){abort_unless($formation->act_status==='final'&&$formation->act_path&&Storage::disk('public')->exists($formation->act_path),404);return Storage::disk('public')->download($formation->act_path,'Acta_'.$formation->act_number.'.pdf');}
}
