<?php
namespace App\Http\Controllers;use App\Http\Requests\{StoreTrainingProgramItemRequest,StoreTrainingProgramRequest};use App\Models\{ActividadPlan,Committee,Empleado,TrainingAudit,TrainingNeed,TrainingProgram,TrainingProgramReview,TrainingTopic};use App\Services\TrainingProgramService;use Barryvdh\DomPDF\Facade\Pdf;use Illuminate\Http\Request;use Maatwebsite\Excel\Facades\Excel;class TrainingProgramController extends Controller{public function index(){$programs=TrainingProgram::forCompany(auth()->user()->company_id)->latest('year')->latest('version')->get();return view('training.programs.index',compact('programs'));}public function store(StoreTrainingProgramRequest$r){$version=TrainingProgram::forCompany($r->user()->company_id)->where('year',$r->integer('year'))->max('version')+1;$p=TrainingProgram::create(array_merge($r->validated(),['company_id'=>$r->user()->company_id,'version'=>$version,'status'=>'draft','prepared_at'=>now(),'created_by'=>$r->user()->id,'updated_by'=>$r->user()->id]));return redirect()->route('training.programs.show',$p)->with('success','Programa anual creado.');}public function show(TrainingProgram$p){$this->own($p);$p->load(['items.needs','items.responsible','reviews.meeting','company']);$topics=TrainingTopic::availableTo($p->company_id)->where('is_active',true)->get();$needs=TrainingNeed::forCompany($p->company_id)->whereIn('status',['approved','planned'])->get();$employees=Empleado::where('company_id',$p->company_id)->get();$committees=Committee::where('perfil_empresa_id',$p->company_id)->get();$planItems=ActividadPlan::all();$pending=TrainingNeed::forCompany($p->company_id)->pendingPlanning()->get();return view('training.programs.show',compact('p','topics','needs','employees','committees','planItems','pending'));}public function item(TrainingProgram$p,StoreTrainingProgramItemRequest$r,TrainingProgramService$s){$this->own($p);$s->editable($p);$d=$r->validated();$needs=$d['need_ids'];unset($d['need_ids']);if($d['planned_date']&&date('Y',strtotime($d['planned_date']))!=$p->year)return back()->withErrors(['planned_date'=>'La fecha debe pertenecer a la vigencia del programa.'])->withInput();$item=$p->items()->create($d);$item->needs()->sync($needs);TrainingNeed::whereIn('id',$needs)->where('company_id',$p->company_id)->update(['status'=>'planned']);if($r->boolean('continue_to_session'))return redirect()->route('training.sessions.create-from-item',$item)->with('success','Actividad planeada. Ahora programe la sesión.');return back()->with('success','Actividad planeada y necesidades relacionadas.');}

    // Paso 2 del flujo guiado "Nueva capacitación": formulario corto que preselecciona la
    // necesidad aprobada y el programa borrador/en revisión vigente, y reutiliza item() arriba.
    public function createItemFromNeed(Request $r)
    {
        $company = auth()->user()->company_id;
        $need = TrainingNeed::forCompany($company)->findOrFail($r->integer('need_id'));
        $program = TrainingProgram::forCompany($company)->whereIn('status', ['draft', 'in_review'])->latest('version')->first();

        if (! $program) {
            return redirect()->route('training.programs.index')
                ->with('warning', 'Primero cree o abra un Programa Anual en borrador antes de programar esta actividad.');
        }

        $topics = TrainingTopic::availableTo($company)->where('is_active', true)->get();
        $employees = Empleado::where('company_id', $company)->get();

        return view('training.programs.create-item', compact('need', 'program', 'topics', 'employees'));
    }public function review(TrainingProgram$p,Request$r){$this->own($p);$d=$r->validate(['review_date'=>'required|date','review_type'=>'required|in:annual,extraordinary','committee_id'=>'nullable|exists:committees,id','committee_meeting_id'=>'nullable|exists:committee_meetings,id','copasst_or_vigia_participation'=>'required|boolean','senior_management_employee_id'=>'nullable|exists:empleados,id','senior_management_participation'=>'required|boolean','conclusions'=>'required|string','improvement_actions'=>'required|string']);$p->reviews()->create(array_merge($d,['reviewed_by'=>$r->user()->id]));$p->update(['reviewed_at'=>now()]);return back()->with('success','Revisión registrada.');}public function submit(TrainingProgram$p,Request$r,TrainingProgramService$s){$this->own($p);$s->submit($p,$r->user()->id);return back()->with('success','Programa enviado a revisión.');}public function approve(TrainingProgram$p,Request$r,TrainingProgramService$s){$this->own($p);$d=$r->validate(['justification'=>'nullable|string|min:10']);$s->approve($p,$r->user()->id,$d['justification']??null);return back()->with('success','Programa aprobado.');}public function activate(TrainingProgram$p,Request$r,TrainingProgramService$s){$this->own($p);$s->activate($p,$r->user()->id);return back()->with('success','Programa activado.');}public function version(TrainingProgram$p,Request$r,TrainingProgramService$s){$this->own($p);return redirect()->route('training.programs.show',$s->version($p,$r->user()->id));}public function pdf(TrainingProgram$p){$this->own($p);$p->load(['company','items.needs','items.responsible','reviews']);return Pdf::loadView('pdf.training_program',compact('p'))->download("programa-capacitacion-{$p->year}-v{$p->version}.pdf");}public function excel(TrainingProgram$p){$this->own($p);return Excel::download(new \App\Exports\TrainingProgramExport($p),"programa-capacitacion-{$p->year}.xlsx");}private function own($p){abort_unless($p->company_id===auth()->user()->company_id,403);}}
