<?php
namespace App\Http\Controllers;
use App\Http\Requests\{AddTransportServicePassengerRequest,CancelTransportServiceRequest,ExcludeTransportServicePassengerRequest,RescheduleTransportServiceRequest,StoreTransportServiceRequest};
use App\Models\{Empleado,TransportChecklistTemplate,TransportPassenger,TransportPerson,TransportRoute,TransportService,TransportVehicle};
use App\Services\{TransportPassengerResolverService,TransportSchedulingService,TransportServiceActionService,TransportServicePreparationService};
use Carbon\Carbon;use Illuminate\Http\Request;
class TransportServiceController extends Controller{
 public function index(Request$r){$c=$r->user()->company_id;$date=$r->filled('date')?Carbon::parse($r->input('date')):today();$q=TransportService::forCompany($c)->with(['vehicle','driver.employee','monitor.employee','passengers'])->whereDate('service_date',$date)->orderBy('scheduled_start_at');foreach(['transport_route_id','planned_vehicle_id','planned_driver_id','planned_monitor_id','shift','service_type','status']as$f)if($r->filled($f))$q->where($f,$r->$f);return view('transport.operation.index',['services'=>$q->get(),'date'=>$date]+$this->resources($c));}
 public function create(){return view('transport.services.create',$this->resources(auth()->user()->company_id));}
 public function store(StoreTransportServiceRequest$r,TransportSchedulingService$service){$s=$service->create($r->validated(),$r->user()->company_id,$r->user()->id);return redirect()->route('transport.services.show',$s)->with('success','Servicio individual programado.');}
 public function show(TransportService$service,TransportServicePreparationService$preparation,TransportServiceActionService$actions){$this->own($service);$service->load(['route','schedule','vehicle','driver.employee','monitor.employee','actualVehicle','actualDriver.employee','actualMonitor.employee','passengers.passenger','passengers.stop','changes','preoperationalCheck.results.item','issues.evidence','arrivalSignature','receiver']);return view('transport.services.show',['service'=>$service,'checklist'=>$preparation->checklist($service),'actions'=>$actions->describe($service),'templates'=>TransportChecklistTemplate::forCompany($service->company_id)->with('items')->where('status','active')->get(),'employees'=>Empleado::where('company_id',$service->company_id)->active()->orderBy('nombre_completo')->get(),'availablePassengers'=>TransportPassenger::forCompany($service->company_id)->where('status','active')->orderBy('name')->get()]+$this->resources($service->company_id));}
 public function resolve(TransportService$service,TransportPassengerResolverService$resolver){$this->own($service);$count=$resolver->resolve($service,auth()->id());return back()->with('success',"Se resolvieron {$count} pasajeros esperados.");}
 public function confirmPassengers(TransportService$service,TransportPassengerResolverService$resolver){$this->own($service);$resolver->confirm($service,auth()->id());return back()->with('success','Lista de pasajeros confirmada y congelada para este servicio.');}
 public function prepare(TransportService$service,TransportServicePreparationService$preparation){$this->own($service);$preparation->prepare($service,auth()->id());return back()->with('success','Servicio preparado y pasajeros congelados.');}
 public function reschedule(RescheduleTransportServiceRequest$r,TransportService$service,TransportSchedulingService$scheduling){$this->own($service);$scheduling->reschedule($service,$r->validated(),$r->user()->id);return back()->with('success','Servicio reprogramado con historial.');}
 public function cancel(CancelTransportServiceRequest$r,TransportService$service,TransportSchedulingService$scheduling){$this->own($service);$scheduling->cancel($service,$r->validated('reason'),$r->user()->id);return back()->with('success','Servicio cancelado sin eliminar su historial.');}
 public function add(AddTransportServicePassengerRequest$r,TransportService$service,TransportSchedulingService$scheduling){$this->own($service);$p=TransportPassenger::forCompany($service->company_id)->findOrFail($r->validated('transport_passenger_id'));$scheduling->addPassenger($service,$p,$r->validated('reason'),$r->user()->id);return back()->with('success','Pasajero excepcional agregado.');}
 public function exclude(ExcludeTransportServicePassengerRequest$r,TransportService$service,int$passenger,TransportSchedulingService$scheduling){$this->own($service);$scheduling->excludePassenger($service,$passenger,$r->validated('reason'),$r->user()->id);return back()->with('success','Pasajero excluido sólo de este servicio.');}
 private function resources(int$c):array{return['routes'=>TransportRoute::forCompany($c)->where('status','active')->orderBy('name')->get(),'vehicles'=>TransportVehicle::forCompany($c)->where('status','active')->get(),'drivers'=>TransportPerson::forCompany($c)->with('employee')->where('status','active')->where('is_driver',1)->get(),'monitors'=>TransportPerson::forCompany($c)->with('employee')->where('status','active')->where('is_monitor',1)->get()];}
 private function own($m):void{abort_unless((int)$m->company_id===(int)auth()->user()->company_id,404);}
}
