<?php
namespace App\Http\Controllers;
use App\Http\Requests\{CompleteTransportPreOperationalRequest,RegisterTransportArrivalRequest,RegisterTransportDepartureRequest,StoreTransportServiceIssueRequest};
use App\Models\{Empleado,TransportPassenger,TransportService,TransportServiceIssue};
use App\Services\{TransportAuditService,TransportOperationService};
use App\Traits\AuthorizesCompanyOwnership;
use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;

class TransportOperationController extends Controller
{
 use AuthorizesCompanyOwnership;
 public function preoperational(CompleteTransportPreOperationalRequest $r,TransportService $s,TransportOperationService $op){$this->own($s);$op->completePreoperational($s,$r->validated(),$r->user()->id);return back()->with('success','Control preoperacional completado.');}
 public function departure(RegisterTransportDepartureRequest $r,TransportService $s,TransportOperationService $op){$this->own($s);$op->departure($s,$r->validated(),$r->user()->id);return back()->with('success','Salida registrada con la hora del servidor.');}
 public function passenger(Request $r,TransportService $s,int $passenger,TransportOperationService $op){$this->own($s);$data=$r->validate(['status'=>'required|in:boarded,absent','observation'=>'nullable|string|max:500']);$op->passenger($s,$passenger,$data['status'],$r->user()->id,$data['observation']??null);return back()->with('success','Estado del pasajero actualizado.');}
 public function resource(Request $r,TransportService $s,string $type,TransportOperationService $op){$this->own($s);$data=$r->validate(['resource_id'=>'required|integer','reason'=>'required|string|min:10|max:1000']);$op->changeResource($s,$type,$data['resource_id'],$data['reason'],$r->user()->id);return back()->with('success','Recurso real actualizado sin modificar la programación original.');}
 public function issue(StoreTransportServiceIssueRequest $r,TransportService $s,TransportAuditService $audit){$this->own($s);if(!in_array($s->status,['preoperational','in_progress','arrived','interrupted']))return back()->with('error','No se puede registrar una novedad en un servicio con este estado.');$d=$r->safe()->except('evidence');$issue=$s->issues()->create($d+['company_id'=>$s->company_id,'occurred_at'=>now(),'status'=>'open','reported_by'=>$r->user()->id]);if($r->hasFile('evidence')){$file=$r->file('evidence');$bytes=file_get_contents($file->getRealPath());$path=$file->store("transport/issues/{$s->uuid}",config('attendance.disk','local'));$issue->evidence()->create(['original_name'=>$file->getClientOriginalName(),'mime_type'=>$file->getMimeType(),'size'=>$file->getSize(),'file_path'=>$path,'file_hash'=>hash('sha256',$bytes),'uploaded_by'=>$r->user()->id]);}$audit->record($s->company_id,'transport_issue_created','service',$s->id,$r->user()->id,['issue_id'=>$issue->id]);return back()->with('success','Novedad operacional registrada.');}
 public function resolve(Request $r,TransportService $s,TransportServiceIssue $issue,TransportAuditService $audit){$this->own($s);abort_unless($issue->transport_service_id===$s->id,404);$data=$r->validate(['action_taken'=>'required|string|min:5|max:4000']);$issue->update(['action_taken'=>$data['action_taken'],'status'=>'resolved','resolved_at'=>now(),'resolved_by'=>$r->user()->id]);$audit->record($s->company_id,'transport_issue_resolved','service',$s->id,$r->user()->id,['issue_id'=>$issue->id]);return back()->with('success','Novedad resuelta.');}
 public function arrival(RegisterTransportArrivalRequest $r,TransportService $s,TransportOperationService $op){$this->own($s);$data=$r->validated();if(!empty($data['receiver_employee_id'])&&!Empleado::where('company_id',$s->company_id)->whereKey($data['receiver_employee_id'])->exists())return back()->with('error','El empleado receptor seleccionado no pertenece a esta empresa.');$op->arrival($s,$data,$r->user()->id);return back()->with('success','Llegada registrada con evidencia de recepción.');}
 public function close(Request $r,TransportService $s,TransportOperationService $op){$this->own($s);$op->close($s,$r->user()->id);return back()->with('success','Servicio cerrado.');}
 public function interrupt(Request $r,TransportService $s,TransportOperationService $op){$this->own($s);$d=$r->validate(['reason'=>'required|string|min:10|max:2000']);$op->interrupt($s,$d['reason'],$r->user()->id);return back()->with('success','Servicio interrumpido y conservado en el historial.');}
 public function signature(TransportService $s){$this->own($s);abort_unless(auth()->user()->can('transporte.firmas.ver'),403);$sig=$s->arrivalSignature()->firstOrFail();return Storage::disk(config('attendance.disk','local'))->response($sig->file_path,'firma-llegada.png',['Cache-Control'=>'private, no-store']);}
 public function correct(Request $r,TransportService $s,string $field,TransportOperationService $op){$this->own($s);$data=$r->validate(['value'=>'required|date','reason'=>'required|string|min:10|max:2000']);$op->correctTime($s,$field,$data['value'],$data['reason'],$r->user()->id);return back()->with('success','Registro corregido con historial de auditoría.');}
 public function issueEvidence(TransportService $s,TransportServiceIssue $issue,int $evidence){$this->own($s);abort_unless($issue->transport_service_id===$s->id,404);$file=$issue->evidence()->findOrFail($evidence);return Storage::disk(config('attendance.disk','local'))->response($file->file_path,$file->original_name,['Cache-Control'=>'private, no-store']);}
}
