<?php
namespace App\Models;
use Illuminate\Database\Eloquent\{Builder,Model};
class TransportService extends Model {
 protected $fillable=['company_id','uuid','transport_route_id','transport_schedule_id','service_date','service_type','shift','scheduled_start_at','scheduled_arrival_at','planned_vehicle_id','planned_driver_id','planned_monitor_id','actual_vehicle_id','actual_driver_id','actual_monitor_id','actual_start_at','actual_arrival_at','departure_odometer','arrival_odometer','departure_registered_by','arrival_registered_by','arrival_receiver_employee_id','arrival_receiver_name','arrival_observation','operational_route_notes','closed_at','closed_by','interrupted_at','interrupted_by','interruption_reason','route_name_snapshot','origin_snapshot','destination_snapshot','status','passenger_snapshot_status','generation_source','notes','cancellation_reason','cancelled_at','cancelled_by','created_by','updated_by'];
 protected $casts=['service_date'=>'date','scheduled_start_at'=>'datetime','scheduled_arrival_at'=>'datetime','actual_start_at'=>'datetime','actual_arrival_at'=>'datetime','closed_at'=>'datetime','interrupted_at'=>'datetime','cancelled_at'=>'datetime','departure_odometer'=>'decimal:2','arrival_odometer'=>'decimal:2'];
 public function getRouteKeyName(){return 'uuid';} public function scopeForCompany(Builder $q,int $id):Builder{return $q->where('company_id',$id);}
 public function route(){return $this->belongsTo(TransportRoute::class,'transport_route_id');} public function schedule(){return $this->belongsTo(TransportSchedule::class,'transport_schedule_id');}
 public function vehicle(){return $this->belongsTo(TransportVehicle::class,'planned_vehicle_id');} public function driver(){return $this->belongsTo(TransportPerson::class,'planned_driver_id');} public function monitor(){return $this->belongsTo(TransportPerson::class,'planned_monitor_id');}
 public function actualVehicle(){return $this->belongsTo(TransportVehicle::class,'actual_vehicle_id');} public function actualDriver(){return $this->belongsTo(TransportPerson::class,'actual_driver_id');} public function actualMonitor(){return $this->belongsTo(TransportPerson::class,'actual_monitor_id');}
 public function passengers(){return $this->hasMany(TransportServicePassenger::class);} public function changes(){return $this->hasMany(TransportServiceChange::class);} public function alerts(){return $this->hasMany(TransportAlert::class);}
 public function preoperationalCheck(){return $this->hasOne(TransportPreoperationalCheck::class);} public function issues(){return $this->hasMany(TransportServiceIssue::class);} public function arrivalSignature(){return $this->hasOne(TransportArrivalSignature::class);} public function receiver(){return $this->belongsTo(Empleado::class,'arrival_receiver_employee_id');}
 public function getExpectedPassengerCountAttribute():int{return $this->passengers->whereNotIn('status',['excluded'])->count();} public function getActualPassengerCountAttribute():int{return $this->passengers->whereIn('status',['boarded','completed'])->count();}
}
