@extends('layouts.app')
@section('content')
<div class="container-fluid my-4"><h2>Capacitaciones SG-SST</h2>@include('training.partials.nav')
@foreach($alerts as $alert)<div class="alert alert-warning">{{ $alert }}</div>@endforeach
<div class="row"><div class="col-md-4"><div class="card"><div class="card-body"><h5>Programa actual</h5><h3>{{ $program?->title ?? 'No creado' }}</h3><span class="badge badge-info">{{ $program?->status ?? 'Pendiente' }}</span></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><h5>Necesidades</h5><p>{{ $identified }} identificadas<br>{{ $planned }} planificadas<br><b>{{ $pending }} pendientes</b></p></div></div></div><div class="col-md-4"><div class="card"><div class="card-body"><h5>Actividades</h5><h3>{{ $activities }} programadas</h3><p>Ejecución pendiente — CAP-2</p></div></div></div></div>
<div class="row mt-3"><div class="col-md-3"><div class="card"><div class="card-body"><h5>Ejecución</h5><b>{{$executed}} ejecutadas</b><br>{{$partial}} parciales</div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><h5>Cobertura acumulada</h5><h3>{{$coverage}}%</h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><h5>Próxima sesión</h5>@if($nextSession)<b>{{$nextSession->title}}</b><br>{{$nextSession->scheduled_start_at->format('d/m/Y H:i')}}@else Sin sesiones próximas @endif</div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><h5>Inducciones pendientes</h5><h3>{{$inductionPending}}</h3><a href="{{route('training.inductions.index')}}">Gestionar</a></div></div></div></div>
<div class="row mt-3"><div class="col-md-3"><div class="card"><div class="card-body"><h5>Evaluaciones pendientes</h5><h3>{{$pendingEvaluations}}</h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><h5>Resultado de evaluación</h5><h3>{{$approvalRate}}%</h3><small>Aprobación, no competencia</small></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><h5>Refuerzos pendientes</h5><h3>{{$pendingReinforcements}}</h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><h5>Credenciales por vencer</h5><h3>{{$expiringCredentials}}</h3></div></div></div></div>
<div class="mt-3"><a class="btn btn-primary" href="{{ route('training.needs.index') }}">Nueva necesidad</a> <a class="btn btn-outline-primary" href="{{ route('training.topics.index') }}">Nuevo tema</a> <a class="btn btn-success" href="{{ route('training.programs.index') }}">Programa anual</a></div></div>
@endsection
